src/client/refresh/r_mesh.c
src/client/refresh/r_surf.c

This addresses issue #54. This commit also removes a couple of redundant OpenGL calls.

Apply gl_overbrightbits to regular meshes.

---

.gitignore

These files can be securely ignored as they are always re-generated.

Also ignore .d files as they got generated every time.

---

src/backends/unix/signalhandler.c
src/client/menu/menu.c
src/game/savegame/savegame.c

Debian's `lintian` tool checks for common mistakes in source and binary packages. One of its checks is to look for common mis-spellings in the binaries.
Based on a patch by Fabian Greffrath against an earlier version of yquake2.

Fix spelling errors detected by lintian

---

Makefile
src/common/header/common.h
src/common/misc.c
src/game/savegame/savegame.c

For deterministic/reproducible builds (where the same source and
toolchain can be verified to produce the same binary, allowing
maliciously substituted binaries to be detected) it is desirable to
take the software's idea of the build date from the build system;
otherwise, the real-time clock at the time of building affects the
result, making it non-reproducible.
SOURCE_DATE_EPOCH is a distribution-neutral specification for how
to do that. It is meant to be set by meta-build systems such as
dpkg or RPM, using a date/time that is already part of the source code,
for example the date of the latest git commit, the date in
the package's debian/changelog, or the date in the RPM spec file.
See https://reproducible-builds.org/specs/source-date-epoch/ for the
specification of SOURCE_DATE_EPOCH, or …

Override __DATE__ from SOURCE_DATE_EPOCH if set

---

Makefile
src/backends/generic/qal.c
src/backends/unix/system.c

In Linux distributions, having the executable depend on the right
libraries and arrange for them to be installed is straightforward,
and there's a lot of infrastructure for tracking which library
version a particular executable needs, including making sure we have
a version that contains all of the symbols that were used. Loading
libopenal at runtime defeats that infrastructure.
The ability to substitute a different-but-compatible libopenal,
or operate with reduced functionality without libopenal, might
still be desirable for generic/portable binary releases.
The CMake build system already linked the executable to
${OPENAL_LIBRARY} anyway, so it is already a hard dependency in that
build system.

Optionally link libopenal at compile time

---

src/game/savegame/savegame.c

The game code does not include common.h, so it needs to redo this
part for builds without SOURCE_DATE_EPOCH, where BUILD_DATE will
not have been passed in from the outside.
Signed-off-by: Simon McVittie <smcv@debian.org>

savegame: ensure that BUILD_DATE is defined

---

src/client/refresh/gl3/gl3_main.c
src/client/refresh/gl3/gl3_mesh.c
src/client/refresh/gl3/header/local.h

Simple shadows for GL3, enable with `gl_shadows 1`.
Look like GL1 `gl_shadows` + `gl_stencilshadows`, so it uses the stencil buffer to avoid ugly artifacts, but it still overlaps at edges etc,  no fancy shadow volumes here.

GL3 shadows

---

src/client/refresh/gl3/gl3_main.c
src/client/refresh/gl3/gl3_mesh.c
src/client/refresh/gl3/header/local.h

The model shadows are rendered after all entities are rendered, fixes #194 
refactored gl3_mesh.c to use less global variables (see commit for details)

GL3: Render Model shadows last, refactor gl3_mesh.c

---

stuff/cvarlist.md

split up into General, Audio, Generic Rendering, GL1 and GL3.

Revamp cvar list (split up in sections, improve gl_*/gl3_* descriptions)

---

Makefile

Commit 883781c selected these paths for all OSs, but when linking to
a system copy of OpenAL for Linux distribution binaries we want the
normal OpenAL in /usr.

Only use /usr/local/opt/openal-soft on Darwin

---

Makefile

Breaks the build since version 7.00
Results in errors (a lot cropped):
```
===> LD release/baseq2/game.so                                                                                                                                                                                                    
cc build/baseq2/src/common/shared/flash.o build/baseq2/src/common/shared/rand.o build/baseq2/src/common/shared/shared.o build/baseq2/src/game/g_ai.o build/baseq2/src/game/g_chase.o build/baseq2/src/game/g_cmds.o build/baseq2/s
rc/game/g_combat.o build/baseq2/src/game/g_func.o build/baseq2/src/game/g_items.o build/baseq2/src/game/g_main.o build/baseq2/src/game/g_misc.o build/baseq2/src/game/g_monster.o build/baseq2/src/game/g_phys.o build/baseq2/src/
game/g_spawn.o …
```

Don't use -Wl,--no-undefined on OpenBSD

---

CMakeLists.txt

The variable yquake2RendererLinkerFlags is used to store the linker flags for opengl but the empty variable yquake2OpenGLLinkerFlags is used when linking libraries to the renderer.
Also there's no need to link the opengl libs to the opengl3 renderer when the glad extension loader is being used.

Fix opengl linking for the renderers.

---

src/client/sound/sound.c

Spotted while compiling with clang.

name field is not a pointer.

---

src/backends/generic/vid.c
src/backends/sdl/refresh.c
src/client/refresh/gl/r_main.c
src/client/refresh/gl/r_sdl.c
src/client/refresh/gl3/gl3_main.c
src/client/refresh/gl3/gl3_sdl.c

(This has been lying around for almost 3 monts, totally forgot to merge this before..)
For some fucking reason, if you set an unsupported
SDL_GL_MULTISAMPLESAMPLES value on Windows (at least Win10 with Intel GPU
drivers, there 16 is unsupported), creating the Window and OpenGL context
will succeed, but you'll get Microsofts stupid GDI OpenGL software
implementation that only supports OpenGL 1.1.
Before these fixes, the GL3 renderer would just crash and the GL1 renderer
would fail to load, which caused the game to run in the background:
No Window, no Input, but sound was playing..
Now this problem should be handled properly and if initialization fails,
the rendering backend will be considered not working, and it will
try the gl1 backend next, and if that also fails it'll give up and exit …

Fix crash on Windows if MSAA is set to a value the driver doesn't support

---

Makefile
src/win-wrapper/wrapper.c

Apparently something (possibly nvidia's driver) on some windows installations has some stupid application profile for quake2.exe that breaks mouse input if the console has been opened, see #257 
The workaround is to rename quake2.exe to yquake2.exe and provide a wrapper quake2.exe that just calls the real one for backwards compatibility.

quake2.exe => yquake2.exe; quake2.exe wrapper

---

Makefile

One of the de facto standard interfaces used for cross-compiling is to override PKG_CONFIG at the same time as overriding CC, for example to `arm-linux-gnueabihf-pkg-config` and `arm-linux-gnueabihf-cc`. In particular, this is done when Debian packages are cross-compiled.

Make uses of pkg-config cross-compilation-friendly

---

src/backends/sdl/input.c

The misspelling of "controller" was detected by Debian's Lintian tool.

sdl/input: Fix spelling and grammar in a log message

---

CMakeLists.txt

Hi,
'GREATER_EQUAL' was introduced in CMake 3.7:
https://cmake.org/cmake/help/v3.7/release/3.7.html#commands
CMakeList.txt states that minimum required version of CMake is 3.0. So please use 'GREATER' instead of 'GREATER_EQUAL'.
Please also note, that Ubuntu 16.04 has CMake 3.5, so using 'GREATER_EQUAL' will break build process for this platform.
Best regards,

Use CMake 'GREATER' instead of 'GREATER_EQUAL'.

---

Makefile
src/backends/unix/network.c
src/backends/windows/network.c

When hosting or joining a server via a IPV6 address no connection can be made. This is because of the ipv6 address '::' which should be '::1'. This PR fixes this mistake.

Fix IPV6 networking

---

Makefile

There were issues with the macOS build.
`
===> Building quake2
/Applications/Xcode.app/Contents/Developer/usr/bin/make release/quake2
make[1]: *** No rule to make target `build/client/src/backends/generic/misc.o', needed by `release/quake2'.  Stop.
make: *** [client] Error 2
`
`Elkan:yquake2 Elkan$ make -v
GNU Make 3.81
Copyright (C) 2006  Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.
This program built for i386-apple-darwin11.3.0
`
This fixes the build on MacOS.

Fix the MacOS build

---

src/backends/unix/shared/hunk.c
src/client/refresh/gl1/gl1_md2.c
src/client/refresh/gl1/gl1_model.c
src/client/refresh/gl1/gl1_sp2.c
src/client/refresh/gl3/gl3_md2.c
src/client/refresh/gl3/gl3_model.c
src/client/refresh/gl3/gl3_sp2.c
src/client/refresh/soft/header/local.h
src/client/refresh/soft/sw_aclip.c
src/client/refresh/soft/sw_alias.c
src/client/refresh/soft/sw_bsp.c
src/client/refresh/soft/sw_edge.c
src/client/refresh/soft/sw_light.c
src/client/refresh/soft/sw_main.c
src/client/refresh/soft/sw_model.c
src/client/refresh/soft/sw_poly.c
src/client/refresh/soft/sw_polyse.c
src/client/refresh/soft/sw_rast.c
src/client/refresh/soft/sw_sprite.c
src/client/refresh/soft/sw_surf.c

* Cleanup soft render little more
* Support for big bsp with 32k+ marksurfaces.
* allocate hunks with relation to original file size.
* save hunk size to size_t typed variable for unix systems.

Softrender cleanup

---

src/client/menu/menu.c
src/common/filesystem.c

I noticed these issues while making some changes for CTF in the "Start Server" menu for myself:
1. Case-insensitivity isn't working for directly loading files when YQ2 is located in a directory tree with capitalization (when it is also executed from a different directory than where it resides).
2. It looks like there's a typo in the code that would prevent the Rogue dmflags from displaying in the menu.  (I don't have the mission pack to verify that, though.)
Also, let me know if you'd be interested in adding the CTF-specific game options to the "Start Server" menu and "dmflags" menu, and I'll send those through.

Minor bug-fixes: Case-insensitive file loading & Rogue dmflags display

---

src/backends/windows/main.c

When cross compiling for Windows on a Linux environment case sensitivity matters for file names.

Fix case error for linux -> win32 cross compile

---

src/client/menu/menu.c

While working on my personal project using your quake 2 fork I noticed issues parsing my `map.lst` file, I had to change the line terminator from `\r` to `\n`. Not sure if there are other types of `map.lst` files with a different format to them. Perhaps the better solution would be using `||` and testing for both conditions.
The original code gave me an `No maps in maps.lst` error.
My `maps.lst` file contents are the following:
```
q2dm1 "The Edge"
q2dm2 "Tokay's Towers" 
q2dm3 "The Frag Pipe" 
q2dm4 "Lost Hallways"
q2dm5 "The Pits"
q2dm6 "Lava Tomb"
q2dm7 "The Slimy Place"
q2dm8 "WareHouse"
``` 
_Thanks for the cleaned up Quake 2 code :+1: !_

Fixed menu code to correctly parse maps.lst file.

---

doc/04_cvarlist.md
src/client/refresh/gl1/gl1_model.c
src/client/refresh/gl3/gl3_light.c
src/client/refresh/gl3/gl3_main.c
src/client/refresh/gl3/gl3_model.c
src/client/refresh/gl3/gl3_sdl.c
src/client/refresh/gl3/gl3_shaders.c
src/client/refresh/gl3/gl3_surf.c
src/client/refresh/gl3/gl3_warp.c
src/client/refresh/gl3/header/local.h

Seems like AMDs Windows driver doesn't like it when we call `glBufferData()` *a lot* (other drivers, incl. Intels and, IIRC, the AMD legacy driver used for the Radeon HD 6850 don't seem to care as much).
Even on an i7-4771 with a Radeon RX 580 I couldn't get stable 60fps on Windows without this workaround (the open source Linux driver is ok).
The be enabled/disabled with the gl3_usebigvbo CVar; by default it's -1 which means "enable if AMD driver is detected".
Enabling it when using a nvidia GPU with their proprietary drivers reduces the performance to 1/3 of the fps we get without it, so it indeed needs to be conditional...
So yeah, this is our first GPU-vendor specific workaround :-/
I'm not 100% sure about the code yet, I especially wonder if I should add some padding between the data …

Make gl3 fast with AMDs Windows drivers

---

src/client/cl_keyboard.c
src/client/header/keyboard.h
src/client/input/sdl.c
src/client/menu/menu.c

There's an "enable alt joy keys" command now. If a key is bound to that
command, all joystick buttons (incl. hat and triggers) are turned from
K_JOYx into K_JOYx_ALT, which allows two keybindings on the same key,
one with the altselector pressed and one without.
If there's no keybinding for K_JOYx_ALT, it will use the binding for
just K_JOYx as a fallback (if it exists).
This is especially handy to create direct bindings for all the weapons
on the (limited amount of) Joystick buttons.
This is inspired by #387 / #388

Allow second layer of keybindings for controllers, refs #387

---

CMakeLists.txt

This resolves a couple issues, allowing all targets to be successfully built for Windows using CMake.
I'm assuming that SDL is linked with q2ded on Windows for Unicode command line support. Would it be worth using `wmain` directly in order to remove that dependency?

CMake fixes for Windows

---

src/client/cl_keyboard.c

Scroll functionality for both the mouse wheel and buttons 4 & 5 was already implemented in `Key_Console()`. However, those keycodes never reached that function as they were not declared in `consolekeys`.
Once that issue was fixed another appeared. If those keycodes were unbound, warning messages would then appear in instances where the console was technically open but `cls.key_dest` was not set to `key_console` (e.g. fullscreen console).
In order to fix this unbound key warnings now only print when in-game. This is the only time when the warnings are actually useful as `Con_DrawNotify()` is only called during gameplay.

Allow scrolling with mouse in console

---

src/client/menu/videomenu.c
src/client/vid/glimp_sdl.c
src/client/vid/header/vid.h

This pull request adds an option to the "VIDEO" menu that allows you to specify which display/monitor you want the game to run on, and can be seen in the screenshot.
If this option is not desired, please feel free to disregard this pull request.
This adds a new archived Cvar "vid_displayindex" which the video menu sets and signals a restart with the "restart" qboolean in ApplyChanges()
Extra Notes:
The last_position_x and last_position_y variables don't actually seem to be used, though the window position is still stored in them.
I have a habit of adding extra spaces around parenthesis, and I notice I still accidentally did that, but if you prefer I conform to the no-spaces coding style, I can throw that in an extra commit.
If you have any other questions/comments/concerns, please let me …

Multi-Monitor Management

---

src/client/refresh/soft/header/local.h
src/client/refresh/soft/sw_draw.c
src/client/refresh/soft/sw_main.c

* Fixed incorrect pointer arithmetic in RE_BufferDifferenceStart, we can compare integers instead pixel_t, but should use pixel_t pointers in base.
```
back_buffer = (int*)swap_frames[0] + vmin * vid.width;
```
vs
```
back_buffer = (int*)(swap_frames[0] + vmin * vid.width);
```
* Added framebuffer damage based logic for get posible start/end diffeences from sprite render code.

Fix overrun in RE_BufferDifferenceStart

---

src/client/refresh/gl1/header/qgl.h

on Darwin, Mojave has deprecated it in favor of Metal,
here we silent the lengthy build warning.

Silence deprecation warning with OpenGL.

---

README.md

if => in (in the last official release)
build => built (is built upon)

Typos in README: if => in, build => built

---

src/game/g_monster.c
src/game/monster/parasite/parasite.c

I noticed the bugfix to asdress https://github.com/yquake2/yquake2/issues/440 was incomplete. This pull request completes it by setting the parasite's viewheight to 16, ensuring traces don't shoot over its bbox. I also added if (!self->viewheight) checks to swimmonster and flymonster as well for consistency with walkmonster.

Full bugfix for monsters not fighting parasites

---

src/client/sound/sound.c

S_StartSound inserts sounds with same mix time after the first inserted such sound, instead of after the last one.
#448

Fix the pending sound list sorting

---

src/game/monster/insane/insane.c

This was a little thing partially caused by the change in sound prioritization. Insane marines will no longer scream or moan for 1 second after taking damage. To my knowledge the insane marines are the only enemy type in the game who need this special handling of sound priority. This also fixes the sound issue on nightmare difficulty, since they don't go into pain frames they constantly moan and scream which frequently would cut off the pain sound. I will also add pull requests for xatrix and rogue to address this there.

Fix for insane marines not always playing pain sounds

---

src/game/g_monster.c

This pull request addresses issue https://github.com/yquake2/yquake2/issues/458.
Long story short, it was caused by triggered spawn monsters calling monster_start_go() twice. First during initial spawn and then again when they are spawned by being triggered. The first call works correctly but the second call actually clears the target and sets the monster to stand still.
I fixed this by making triggered spawn monsters only call monster_start_go() once - when they get triggered.
You can use the security.ent test file from the bug report to see that when you pick up the shotgun, the triggered guard moves to his marker like the other guard does.

Triggered spawned monsters use path_corner correctly

---

src/game/monster/brain/brain.c
src/game/monster/chick/chick.c
src/game/monster/gunner/gunner.c
src/game/monster/infantry/infantry.c
src/game/monster/medic/medic.c
src/game/monster/soldier/soldier.c

This pull request fixes bug https://github.com/yquake2/yquake2/issues/456 by adding a call to FoundTarget() after assigning the enemy in the dodge functions.

Fix monsters being disoriented after ducking

---

src/client/refresh/soft/sw_draw.c

If we have picture scaled and we can reuse same picture row in 1+ lines, code scale first one horizontally and copy by memcpy next one's verticaly. 
This code part have used in the intro videos.

Copy drawn lines if picture scaled

---

doc/040_cvarlist.md

Added documentation for coop_baseq2 cvar. I wasn't sure where to put it so I put it under the General section of the cvar docs. If you want it somewhere else then let me know and I'll move it.

coop_baseq2 documentation added under General section in cvar docs

---

src/client/refresh/gl1/gl1_draw.c
src/client/refresh/gl1/gl1_image.c
src/client/refresh/gl3/gl3_draw.c
src/client/refresh/gl3/gl3_image.c
src/client/refresh/gl3/gl3_misc.c
src/client/refresh/gl3/header/local.h

and make sure that after vid_restart (or starting the game) it's used
correctly in GL3.
While at it, made sure that it's *not* applied to textures from
gl_nolerp_list, because they're supposed to always use GL_NEAREST
independent of this setting (used so console font and crosshairs don't
look blurry)

Use gl_texturemode for UI and skies as well, fixes #489 and #491

---

src/game/header/local.h
src/game/monster/insane/insane.c

Fixes bug https://github.com/yquake2/yquake2/issues/495. As detailed in the comments, this was caused by using the delay struct member for storing data specific to the insane-marines, when in fact it is a generally used value by G_UseTargets.
I fixed it by using a different struct member, fly_sound_debounce_time, this time making absolutely sure there won't be any interference. This struct member is only stored and referenced in one place in the code and only by clients, so interference by the insane marines code is impossible. I added a comment in local.h to explicitly state this new use case for the struct member.

Fix for insane marines not firing deathtarget right away

---

src/client/cl_main.c
src/client/header/client.h
src/client/input/sdl.c

GCC 10 defaults to -fno-common.
Closes #516

Fix build with -fno-common

---

doc/030_configuration.md

Document stated setting 'async 1' disabled asynchronization.  This has been corrected.

Document async configuration correction.

---

CMakeLists.txt
Makefile

Gcc does not support "armv8.0-a", correct value for gcc should be [armv8.0-a](https://gcc.gnu.org/onlinedocs/gcc-9.1.0/gcc/AArch64-Options.html).
```
Error: unrecognized option -march=armv8.0-a
cc1: error: unknown value ‘armv8.0-a’ for ‘-march’
cc1: note: valid arguments are: armv8-a armv8.1-a armv8.2-a armv8.3-a armv8.4-a armv8.5-a native; did you mean ‘armv8.1-a’?
```

fix march armv8

---

src/client/vid/header/ref.h
src/common/header/shared.h
src/game/header/game.h

C11 _Noreturn is only accepted on function declarations, not on function
pointers, so we can't use it on callbacks like game_import_t.error and
refimport_t.Sys_Error. Use a separate macro for those.
The problematic situation doesn't currently happen because the Makefile
hard-codes -std=gnu99, which disables C11 features; but removing
-std=gnu99 (resulting in the compiler's default, currently gnu11) causes
compilation failures with at least gcc 9.x.
---
As discussed briefly on #523, this isn't a practical problem right now, but will become a practical problem if porting to C11 compilers in future.

Add a separate noreturn macro for function pointers

---

src/game/g_items.c
src/game/header/local.h

Fix for bug https://github.com/yquake2/yquake2/issues/547.
I defined a new item flag, IT_INSTANT_USE, that tags items that will be instantly used when picked up in instant-use deathmatch games (deathmatch 1 and dmflags & 16), and I moved the instant use code out of Pickup_Powerup/Pickup_Sphere and into Touch_Item so that the use action overrides the generic pickup sound event, making sure original sound prioritization is maintained.
In my testing I did not discover any unwanted side-effects and the bug is fixed, but I definitely invite others to try this out if they can.

Fix for some items playing wrong sound when instantly used

---

src/game/g_main.c
src/game/header/local.h
src/game/player/weapon.c
src/game/savegame/savegame.c

Awhile ago, I raised issue #379 about whether there was anything that could be done to improve the aiming in-game.
Essentially, I've taken this implementation from Berserker@QuakeII v1.41 that provides the accurate aiming I've desired for so long and placed it behind a CVAR so that it's not enabled by default.
I hope with this change being optional, it can be considered for merging into the port. There are many forum posts online about Quake II and how to get accurate aiming, so I believe this would be desirable by many players.

Implement accurate-aiming CVAR in baseq2 game code.

---

doc/040_cvarlist.md

I noticed this cvar existed while helping with a related issue in yquake2/rogue. Since there is no documentation for it in the doc section I figured I'd write one.

Added doc entry for g_disruptor cvar in GroundZero

---

src/client/refresh/gl3/gl3_shaders.c

Fixes visible primitive edges on liquid surfaces.
See #508 for details.

Move liquid transformations into fragment shader

---

src/game/monster/gunner/gunner.c

This PR fixes bug https://github.com/yquake2/yquake2/issues/571 by adding a check for enemy in gunner_fidget().

Fix for gunner AI freeze bug

---

src/game/monster/boss3/boss31.c

I fixed this in my own project and figured it might be worth to move it to Yamagi Quake 2, since it seems to still have that bug present.
Jorg and Makron models need to be swapped in order for the "hurt" skin to trigger correctly - right now, if Jorg has < 50% of health, it's the Makron's skin that's being replaced instead of the Jorg's. This fix has been tested in vkQuake2 but I see that multi-model entities (I think Jorg is the only one) are handled in the same manner here.

Fixed the Jorg skin bug present since the original Quake 2 release.

---

Makefile

It looks like when you made RPATH optional here: https://github.com/yquake2/yquake2/commit/b48cc4746551061a4135b848fe0679c468442614, the build will try to call the linker with arguments that Mac OS's linker doesn't like. Here is a working fix, I've only tested on Mac OS 10.15.4 though.
I've also added WITH_RPATH to the config info that gets printed when building.
Here's some info about Mac OS's linker, but I'm certainly no expert in it either: https://jorgen.tjer.no/post/2014/05/20/dt-rpath-ld-and-at-rpath-dyld/
Edit: I should include the original failure here as well. This is what happens on master right now when building on Mac OS:
```
===> LD release/quake2
ld: unknown option: -z
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** …
```

Enable rpath with Mac OS linker

---

CMakeLists.txt
Makefile
src/backends/unix/signalhandler.c

Linux/Solaris supports it in the libc however, BSD in general, Haiku
relies on an external library.

backtrace support rework proposal.

---

src/client/menu/menu.c
src/common/filesystem.c
src/common/header/common.h

The data read from "maps.lst" is only ever read once currently, but this change implemented in "FS_BuildGameSpecificSearchPath" causes it to be read again if the "game" cvar/directory is updated.  NOTE: I made this change on an older branch (I'm no longer able to compile locally from about 7.40 onward) but it looks like it shouldn't be impacted by intervening updates.

Start Server Menu: reload "maps.lst" after "game" dir is changed

---

src/backends/unix/shared/hunk.c

which cannot be made executable afterwards.

Hunk: FreeBSD set the map permission to max read and write

---

src/client/cl_keyboard.c
src/common/cmdparser.c
src/common/header/common.h

When using the command to load a map "map x", if one character from the map name is provided, it will try to autocomplete it.
There are 3 possible scenarios I anticipated:
1) The name is an exact match. In this case we do nothing.
2) The name is partially filled out and only 1 match was found. In this case we fill out the rest.
3) The name has many matches. In this case we complete the map name with the characters from the matches until one differs. We also provide the list of the current matches.

map name autocompletion

---

src/client/menu/menu.c
src/common/filesystem.c
src/common/header/common.h

I tried opening the original PR back up, but since I also squashed my commits it was refused. Using Address Sanitizer was easier than I expected.  In addition to correcting my memory leaks, I've also added verification that any params the mod-finder passes to "FS_ListFiles" are formatted properly and any NULL data it returns gets ignored, so mods in "datadir" are located correctly.
I won't be so quick to close a PR next time.

Create "mods" submenu to allow changing "game" cvar via UI

---

src/backends/unix/main.c

Even tough it is a multi user os, due to BeOs heritage and being backwards
compatible with, the desktop runs as root, thus its dog get eaten after all...

Last bit for proper Haiku support.

---

doc/040_cvarlist.md
doc/050_commands.md
src/common/cmdparser.c
src/server/sv_init.c

Add `vstr` command and `nextdemo` variable for support ioquake3 style benchmark commands like:
```
unbindall
timedemo 1
set nextdemo quit
set demoloop "demomap q2demo1.dm2"
vstr demoloop
```
With run by
```shell
./quake2 +exec pts.cfg +set r_mode 5 +set r_fullscreen 0 +set com_speeds 1
``` 
based on [Phoronix Test Suite::OpenArena](https://openbenchmarking.org/innhold/a702bd92a52f8f6d944b7e55ddb6447ee500352b)

Add ioquake3 vstr/nextdemo support

---

src/backends/unix/signalhandler.c

Detected by Lintian, a QA tool used in Debian.

signalhandler: Fix a typo

---

src/client/refresh/vk/header/util.h
src/client/refresh/vk/vk_buffer.c
src/client/refresh/vk/vk_common.c
src/client/refresh/vk/vk_image.c
src/client/refresh/vk/vk_swapchain.c
src/client/refresh/vk/vk_util.c

* Restore memory allocate flags based on GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator 
* Mark non VK_PRESENT_MODE_FIFO_KHR as triple buffered

Restore memory allocation flags from vkquake2

---

src/client/curl/download.c
src/client/menu/menu.c
src/client/refresh/gl1/gl1_main.c
src/common/cmdparser.c
src/common/shared/shared.c

According to the C standard, arguments to the ctype functions must fit into unsigned char (presumably so they can be implemented with simple array access). This causes a build time warning on NetBSD, and may function incorrectly if any UTF-8 strings are used.

Cast arguments to ctype functions to unsigned char

---

src/game/savegame/tables/gamefunc_decs.h

The definition for P_ProjectSource looks like it changed here: https://github.com/yquake2/yquake2/commit/85fb607010ee151b2d6bc217647b41fa687aa0dc#diff-d8777409dd928ef41e564600cc9bdd7ccf260032f18b570a45f750e208936c03R44
This means that the forward declaration is wrong and this pull request fixes that.
I'm not sure if this bad forward declaration caused any issues, but this breaks compilation on my C++ fork of this project and this seemed better to fix here.

Fix P_ProjectSource forward declaration

---

doc/040_cvarlist.md
src/client/refresh/vk/header/local.h
src/client/refresh/vk/vk_draw.c
src/client/refresh/vk/vk_image.c
src/client/refresh/vk/vk_model.c
src/client/refresh/vk/vk_rmain.c
src/client/refresh/vk/vk_rmisc.c
src/client/refresh/vk/vk_warp.c

* remove scrap logic, we have already use sub allocation on vk_util 
* rename gammatable to overbrightable and apply only to world textures
* restore near color only for transparent images (sky and wall can be 0xFF)
* scale 8bit images with enabled retexturing (only for images without override and `vk_retexturing` == 2)
* remove scale down for textures if texture is not power-of-two
* add `vk_nolerp_list` support
* add `vk_retexturing` documetation an enable by default.

Cleanup vulkan code

---

src/client/cl_parse.c
src/client/input/sdl.c

This makes sure key states are reset when the game is reloaded, fixing #633 
Additionally, a debug statement in `sdl.c` has been changed to only output in debug mode as it was making testing hard (couldn't see the messages because it kept overwriting output from quicksave) :)

Flush keys when server data is parsed

---

CMakeLists.txt

Still some alternative oses does not have vulkan support or not full (e.g. Raspberry).

Proposing to make vulkan support eventually optional.

---

Makefile
src/game/savegame/savegame.c

$PROCESSOR_ARCHITECTURE seems to contain the architecture of the host,
but we need the architecture the current MinGW shell is targeting.
$MINGW_CHOST seems to be just that, and on my system it's either
i686-w64-mingw32 (mingw32.exe) or x86_64-w64-mingw32 (mingw64.exe)
(No idea what it looks like for Windows on ARM...)
Now this is correctly set and also SSE is used for floating point math which fixes weird lightmap bugs we've been seeing.

Makefile: Fix architecture detection on Windows

---

src/client/refresh/vk/header/qvk.h
src/client/refresh/vk/vk_common.c
src/client/refresh/vk/vk_draw.c
src/client/refresh/vk/vk_image.c
src/client/refresh/vk/vk_rsurf.c

A couple of skybox-related fixes for Vulkan.
* Fix skybox edges being visible due to texture coordinates by using CLAMP_TO_EDGE addressing in samplers when drawing it
* Fix black pixels along skybox edges due to skyboxes not being watertight.
Fixes #639.

Skybox fixes

---

doc/040_cvarlist.md
src/client/cl_entities.c
src/client/cl_main.c
src/client/header/client.h

Q2PRO already has a `cl_kickangles` cvar (which behaves the same as Yamagi Quake 2's and is also cheat-protected). I think we should rename Yamagi Quake 2's cvar so that Q2PRO users can feel more at home :slightly_smiling_face:

Rename `cl_anglekicks` to `cl_kickangles` for consistency with Q2PRO

---

src/client/refresh/vk/vk_rmisc.c

Minor fix so the number of samples is printed correctly. Related to #646.

Fix text indicating MSAA samples for Vulkan

---

src/backends/unix/shared/hunk.c

Specify correct protection flags when calling mmap() on FreeBSD.
prot | PROT_MAX (prot) are the correct flags because just PROT_MAX
(prot) leaves current protection flags set to PROT_NONE which causes
segmentation fault when reading or writing to the mapped region.

Fix segmentation fault on FreeBSD.

---

src/client/refresh/vk/header/qvk.h
src/client/refresh/vk/vk_common.c
src/client/refresh/vk/vk_rmain.c

While attempting to solve #659 I started the game in fullscreen mode under Gnome and immediately discovered the game entered an infinite renderer restart loop. A few seconds after the renderer had been initialized and was already drawing frames, it received VK_ERROR_OUT_OF_DATE_KHR, which triggered a restart of the whole video system. The game flickered while restarting it (including creating a new game window, I guess) and the story repeated itself a few seconds later.
It appears this is a known issue and also affects or affected [vkQuake](https://github.com/Novum/vkQuake/issues/211) and [vkQuake2](https://github.com/kondrak/vkQuake2/issues/95) and @kondrak solved some months ago by restarting Vulkan without touching the game Window. This pull request implements a similar solution, …

Avoid restarting the whole video on VK_ERROR_OUT_OF_DATE_KHR

---

doc/040_cvarlist.md
src/game/g_main.c
src/game/g_monster.c
src/game/header/local.h
src/game/savegame/savegame.c

Prints a console warning when triggered spawn monsters with no targetname are spawned, and adds a new cvar g_fix_triggered that forces such monsters to spawn normally so they can be fought by the player.

Console warning and fix for triggered monsters with no targetname

---

src/client/refresh/vk/header/local.h
src/client/refresh/vk/header/model.h
src/client/refresh/vk/vk_common.c
src/client/refresh/vk/vk_model.c
src/client/refresh/vk/vk_rmain.c
src/client/vid/vid.c

This pull request essentially fixes two issues:
* ERROR: Mod_PointInLeaf: bad model when restarting the Vulkan renderer. This is solved by making the restart happen at the end of the frame instead of at the beginning of it, and signaling the server the client needs to be re-registered again to rebuild the list of models.
* Memory leak when restarting the Vulkan renderer, due to "models_known" not being freed before allocating it again.
For the first point I used the same approach taken in vkQuake2 of using a global cvar_t called vid_refresh. It's my understanding, from reading other parts of the code, that such an approach is a bit hackish and there should be a message sent from the client  to the server to properly communicate this, but my knowledge of the code base is lacking here, so I …

Vulkan restart tweaks

---

src/client/sound/openal.c

(thus audio backend not yet initialised).

Fix segfault when turning the console before the game is launched

---

doc/020_installation.md
src/game/g_spawn.c
stuff/mapfixes/baseq2/base2.ent
stuff/mapfixes/baseq2/biggun.ent
stuff/mapfixes/baseq2/city1.ent
stuff/mapfixes/baseq2/city2.ent
stuff/mapfixes/baseq2/city3.ent
stuff/mapfixes/baseq2/cool1.ent
stuff/mapfixes/baseq2/lab.ent
stuff/mapfixes/baseq2/train.ent
stuff/mapfixes/juggernaut/jug19.ent

This PR fixes the following bugs: https://github.com/yquake2/yquake2/issues/689 https://github.com/yquake2/yquake2/issues/687
In addition I implemented the code hacks as map fixes (city2, city3, cool1, lab), as well as fixing some additional bugs reported within the bug reports (city1). There are other more minor fixes, like fixing "duration is not a field" console warning in biggun and using an orphaned target_explosion entity in base2.
I removed the code hacks for the following reasons:
1. They make correct configuration more complicated and easy to mess up.
2. They are incomplete. A lot of the bugs found were not addressed by them and the hack for map "lab" was not even fully working.
3. Only the absolutely most die-hard Q2 fans will notice any difference, and even then I doubt they …

Map fixes for old and newly discovered bugs + removed code hacks

---

src/game/g_phys.c
src/game/monster/flipper/flipper.c

This PR fixes bug https://github.com/yquake2/yquake2/issues/704
flipper_dead() sets the dead bbox top and bottom planes incorrectly. This is likely a copy/paste error by id. Unlike most monsters, the flipper's point of origin is at the bottom of its model, so mins[2] is 0, however the death code sets mins to -24 and maxs to -8, not only moving the bbox but actually leaving the model completely.
This makes it hard for the player to know where to actually shoot to gib the dead body, and because the bbox moves, it means it might clip into the world and this causes the entity to freefall forever.
I fixed this by keeping maxs[2] unchanged and doing a trace downwards by 8 units, so mins[2] will be anywhere from 0 to -8 based on if/when the trace hits an obstacle.
I also snuck in a small inuse …

Shark bbox fix and added check for inuse after entity thinking

---

src/game/header/local.h
src/game/player/client.c
src/game/player/view.c

This PR fixes some bugs with player sounds.
* Player does pain sound in lava with godmode on
A small oversight by id. They check for the invul powerup but not the godmode flag. I just added the godmode flag check.
* Player gib sound is rarely replaced by a footstep
This is a side-effect of change to sound priority ordering. Footstep events schedule the sound after the server frame has ends so it would override the gib sound. This was fixed by adding a check for player's health, and also by changing the channel the gib sound is played on (see later).
* Player gib sound is played on the wrong channel
This is a bug in the original game and causes player death scream and gib sound to play over each other if the player is killed by a powerful shotgun blast or is gibbed very quickly after …

Fix for some player sound bugs

---

Makefile

the arch normalization leads to arm32 bit build under mac m1.

build fix proposal on mac where archs are well defined.

---

src/client/menu/menu.c

Keep names consistent with OGG options.

Consistent naming

---

doc/040_cvarlist.md
src/game/g_main.c
src/game/header/local.h
src/game/player/weapon.c
src/game/savegame/savegame.c

This adds the cvar machinegun_norecoil
It should only impact non-deathmatch games.
I used the aimfix cvar as a template to make this change.
The cvar will only work if the game.dll supports it.

Feature request : add cvar to disable machine gun recoil in single player #741 (baseq2)

---

src/common/cmdparser.c

This PR addresses issue https://github.com/yquake2/yquake2/issues/757. It also greatly optimizes and shortens the code by skipping all the unnecessary string copying.

Fixed incorrect handling of - in late args and simplified code

---

src/game/g_ai.c
src/game/g_misc.c
src/game/g_utils.c
src/game/header/local.h

This PR amortizes the issues reported in https://github.com/yquake2/yquake2/issues/759 by easing entity allocation policies.
These are the main points:
* If no free entity is found according to the default policy, a second search is done, ignoring any freetime restrictions
* New function G_SpawnOptional, instead of calling gi.error() it will return NULL, allowing the caller to react more gracefully
* Made ThrowDebris, ThrowGib and AI tempgoals use G_SpawnOptional

Made the game able to handle entity overload better

---

doc/030_configuration.md

This is a tiny change.
Since **Vulkan** was removed from the list as a renderer,  there are only 3 renderers listed.

Change the amount of listed renderers to 3 in documentation

---

src/game/g_func.c
src/game/player/client.c
stuff/mapfixes/baseq2/waste3.ent

This PR addresses https://github.com/yquake2/yquake2/issues/773 and removes the 2 waste3-related map hacks from the code as they are made redundant by the fixed ent file.
In addition to addressing those issues, the enr file also:
1. Fixed wrongly placed message for secret, the message is supposed to be in the target_secret entity but was in the trigger, causing a subtle sound glitch.
2. Fixed 2x monster_gunner with spawnflag 1024. The level designer most likely thought for a moment spawnflags were inclusive rather than exclusive, so viewed 1024 as hard-only rather than 768.
3. Added difficulty spawnflags to entities specific to monsters such as point_combat
4. Added not-deathmatch spawnflag (2048) to entities that are never used/accessible in DM
5. Start missing pumping sound effect for …

Moved code hacks for waste3 to waste3.ent

---

doc/040_cvarlist.md
src/client/refresh/gl1/gl1_draw.c
src/client/refresh/gl1/gl1_image.c
src/client/refresh/gl1/gl1_main.c
src/client/refresh/gl1/header/local.h
src/client/refresh/gl3/gl3_draw.c
src/client/refresh/gl3/gl3_image.c
src/client/refresh/gl3/gl3_main.c
src/client/refresh/gl3/header/local.h

r_lerp_list is to allow exceptions to r_2D_unfiltered (like for having
pixely UI in general, but filtered console background).
r_videos_unfiltered controls whether videos should be filtered or not
I also made r_nolerp_list CVAR_ARCHIVE, like users probably expect it.

Add r_lerp_list and r_videos_unfiltered CVars, fix #800

---

doc/040_cvarlist.md
src/client/input/sdl.c

This allows to redefine the button used as the "**Esc key**" in the SDL controller, by default the _Back/Select/Minus_ (center left) button. Now it can be changed to the _Start/Menu/Plus_ (center right) button, or even to the _Guide/Home/PS_ button (middle of the gamepad, normally big). Requires a game restart to take effect.
Useful for people not happy with the current location of the button.

Added cvar to define SDL gamepad's 'Back' button

---

doc/050_commands.md
src/game/g_cmds.c

Added a command to set a "priority list" of weapons, where the first one available will be selected.
Code has been shamelessly stolen from "cycleweap".
I'm on controller and needed a true "panic button" that doesn't cycle weapons, so I believe this will be useful to other people as well.
If this is accepted, I'll do the pull requests for xatrix and rogue.

Added prefweap command to select weapon by priority

---

doc/040_cvarlist.md
src/client/input/sdl.c

This allows for the loading of _gamecontrollerdb.txt_, database of game controller mappings to be used with SDL2 controllers.
This is _optional_ and its an alternative to the use of setting the SDL_GAMECONTROLLERCONFIG variable to use a gamepad.
It's practical for gamepads that change their GUID when used wired or bluetooth, e.g. Nintendo Switch Pro Controller on Linux.
The text file is usually obtained from https://github.com/gabomdq/SDL_GameControllerDB, and can be put in both the game or "config" directories.

Load gamecontrollerdb.txt for SDL2 joy mappings

---

doc/030_configuration.md

Update to the configuration document.  Removed the deprecated command 'gl_retexturing' and replaced it with the current command 'r_retexturing'

Update retexturing command in configuration document.

---

src/client/header/client.h
src/common/frame.c

* packet framerate doesn't have to be lower than render framerate (unless render framerate is too high) => that 0.95 factor didn't really help
* Improve the max framerate-handling with vsync, around vid_maxfps and the display refreshrate, especially considering the reported display refresh might be a bit too low
* The packet framerate should be a fraction of the render framerate; and it should be between 45 and 90 to prevent movement glitches and such. Setting `cl_maxfps` to `-1` now automatically chooses an appropriate packet framerate that meets those criteria.
- If you want it extra smooth, make sure your render framerate is a multiple of 60Hz (by setting vid_maxfps accordingly, or use vsync with a 60Hz display)
Might fix (or at least improve) #819

Improve timings in Qcommon_Frame()

---

src/client/cl_keyboard.c
src/client/header/keyboard.h
src/client/input/sdl.c
src/client/menu/header/qmenu.h
src/client/menu/menu.c

Currently, _client/input/sdl.c_ handles input from buttons of gamepads/joysticks through SDL_Joystick, which depending on the OS and device may not be the best option. I.e. on MacOS High Sierra, DPad on the Nintendo Switch Pro Controller is not recognized by SDL2 as a hat but as buttons, making it unsuitable to handle game menus (weird, because Cocoa detects it as a hat).
Using SDL_GameController increases compatibility of devices that can be used with YQ2, across any OS supported by SDL2.
"Unrecognized buttons" is no longer an issue since 2.0.14, which recognizes Xbox Elite paddles and other buttons on newer gamepads.
New features:
- Named buttons, consistent across multiple gamepads.
- Improved menu handling on controller: "A" to select, "B" to get back, "Y" to delete.
- Separate menus …

Full transition to SDL_GameController for gamepad usage

---

src/common/shared/shared.c

This might be rare, but I found in Daikatana (which uses the same exact code here) that ASAN triggered a warning from the *s = 0; at the end of Info_SetValueForKey().  This can happen if you have a lot of SERVERINFO (especially custom ones like 'admin', 'email', and 'website') flagged CVARs and someone does a /serverinfo packet.  In Daikatana, it was more prevalent use of UB since the same command was sent every time a map transition happened on a public server to send the serverinfo stats to the gamespy master server.
This bug exists in R1Q2 and all varieties of Info_SetValueForKey() out there that I am aware of.  So the mods would need this fix as well.

Check >= maxsize in Info_SetValueForKey().  Found by ASAN.

---

src/client/cl_inventory.c

When a key/button name is too long, and its bound to an inventory element, its display in the inventory screen misaligns the item it is bound to, even pushing it out of the inventory frame.
This single-line fix limits its display to the maximum of 6 characters the inventory screen allows.

Inventory screen keys/buttons display fix

---

src/client/menu/header/qmenu.h
src/client/menu/menu.c
src/client/menu/qmenu.c

Bug introduced in #841.
Added QMF_INACTIVE.
QMF_INACTIVE menu items are skipped.

Infinite loop in bind menu fix

---

doc/040_cvarlist.md
src/client/cl_main.c
src/client/curl/download.c
src/client/curl/header/download.h

a threshold to abort the download if a certain transfer rate is too low.
Disbabled by default.

client download, adding two new cvar to have the ability to set

---

src/client/input/sdl.c
src/client/menu/menu.c

This is an extension of https://github.com/yquake2/yquake2/pull/849, where gyro aiming was available wireless on Nintendo Switch controllers, but not on PS4 ones (on Windows and Mac). This commit fixes this, even enabling it for the PS5 controller.
What this does is to enable "extended input reports", which handles sensors and rumble through bluetooth.
Wanted to add this on my next PR, but that will take more work and more time.
EDIT: Second commit is something that was requested on Discord. I don't think it hurts to make some people happy...

Gyro aiming through Bluetooth for PS4 & PS5 controllers

---

doc/050_commands.md
src/game/g_cmds.c

This PR makes _cycleweap_ "count the amount of key presses" so it can navigate through its defined list quicker and pull out the desired weapon faster, instead of waiting for the appearance and animation of every weapon on its list.
e.g. you have the following bind:
`bind e "cycleweap weapon_machinegun weapon_chaingun"`
..and you are using any other weapon. By double-tapping "e", you can immediately swap to the chaingun, instead of having to wait for the machinegun to come out first.
It's the equivalent of pressing "4" and quickly after, "5". The press of "5" overrides the previous "4", so the chaingun is the weapon selected at the end.

Faster weapon switching with 'cycleweap'

---

src/game/g_phys.c

This didn't work correctly for multiple reasons:
1. `deltayaw` was wrongly initialized for the pusher itself, rather than for pushed client.
2. `delta_angles[YAW]` is a short, adding plain `amove[YAW]` to it is wrong.
To support yaw angle rotation properly, delta_angles must be interpolated on the client. But this is hardly practical as it would introduce other bugs. Thus, simply remove delta yaw manipulation code altogether.
Fixes infamous Q2 bug when player standing on a blocked lift gets turned into wrong direction.
I'll also send PRs for mission packs if this is accepted.

Remove broken pusher delta yaw manipulation

---

doc/040_cvarlist.md
src/client/header/client.h
src/client/input/sdl.c
src/client/menu/menu.c

I know all of you are very busy right now, but doesn't matter how much time you take to review this, I wanted to do this before the 25th anniversary of Quake II :)
The present PR rewrites joystick reading and handling to introduce some new features that improve thumbsticks' precision and customization.
First, what's been removed:
1. Assigning a function to each stick axis individually.
2. Classic "threshold" deadzones by axis, so no more axial deadzone either.
3. Having "joystick_up" as input for IN_Move(), along with its sensitivity. No gamepad standard uses it, it would be useful only on a ladder or underwater, and only people who have looked at the source code would've known about it, since the name of the function was needed to be assigned to an axis (not present in documentation). …

Improved controller thumbsticks precision + Flick Stick

---

doc/040_cvarlist.md
src/client/input/sdl.c
src/client/menu/header/qmenu.h
src/client/menu/menu.c
src/client/menu/qmenu.c

This adds a couple of spin controls to invert yaw and pitch in the gyro options.
Now sliders are able to use the "absolute value" (ignore negative sign) of its associated cvar, if there's a need for it. This is because the "reversal" of the gyro axes is achieved by converting their sensitivities to a negative value; I believe it's better than adding a new cvar only for this.
Additionally, I resurrected the "in_initjoy" cvar from Quake II 3.21. Fixes #879 
Finally, I added myself to the credits. Thank you for this!

Options to invert gyro axes

---

src/game/g_phys.c

This PR addresses issue https://github.com/yquake2/yquake2/issues/903
The check for level.framenum > 3 ensures items fully settle their physics state before these sounds start playing.

Fix items already in water at level start playing splash sound

---

src/game/g_items.c
src/game/player/hud.c

This PR addresses issue https://github.com/yquake2/yquake2/issues/905.
Other things addressed:
* Out of bounds memory read in loop where keys are removed from player inventory
* Made no-touch power cubes not count towards level.power_cubes, as they will never be picked up anyways

Fix coop power cube related bugs

---

stuff/mapfixes/baseq2/lab.ent

This PR provides an updated lab.ent file that fixes some additional bugs.
* Fixed no-sound button at the start of the level
* Fixed thud sounds heard when activating monsters hit the ground
* Fixed broken trigger links for some target_speaker and/or func_timer
* Fixed derpy medic that raises from the floor (due to sound target / combat target conflicting)
* Removed leftover forcefield disable button from DM mode
* Removed unused entities + optimized trigger chains + flagged lots of SP/coop only entities with the no-DM flag
All my changes can be traced by opening the file with a text editor and using ctrl+F.

Fixed some more minor bugs in Research Lab

---

src/client/menu/menu.c
src/common/filesystem.c

With this change, mods are presented in the following order in its menu:
baseq2 (base game), always first
xatrix (first expansion)
rogue (second expansion)
ctf (official mod by id)
the rest, ordered alphabetically
I think it improves their presentation, since "xatrix" was always presented after "rogue", or "action" before even "baseq2".
Additionally, player skins in their menu are ordered alphabetically in *nix systems, closes #891 .

Mods ordered by priority in menu

---

src/client/menu/menu.c

Skin names for players can have a total length of 32: 15 chars for model + "/" + 15 for skin + "\0". Fixes #918 
Also fixes "playermodels" cmd, which showed "(null)" as a final skin for every model.
Finally, gamepad allowed to select skin in menu.

Fix for crash with long player skin name

---

src/client/menu/menu.c
src/client/sound/ogg.c

This PR addresses issues in https://github.com/yquake2/yquake2/issues/920
Added the missing return statement to playTrack() so ignoretrack0 works as intended.
Added a safety check to ogg music menu option.
Removed playTrack() code from shuffle menu option.

Fixed ignoretrack0 and ogg menu option bugs

---

src/client/header/keyboard.h
src/client/input/sdl.c
src/client/menu/menu.c
src/client/sound/sound.c

This PR replaces the current haptic support, "deprecated" (*) since SDL2.0.14 for gamepads, for a more traditional rumble, supported on a wide range of controllers by SDL2.
I must warn that this development makes visible some issues, but those were already present in the classic haptic work, as tested in a Raspberry Pi 3 B+, the only platform I have an old version of SDL available (2.0.10), where gamepads were still supported by haptic. These are:
- Difficulty to properly identify which sounds come from the player and which come from the environment; the most evident example is that every player's shooting and pain sound will count for feedback in multiplayer. Likewise, a few monster's shots are identified as "from the player"; at least the Phalanx shots from the Gladiator Beta of the …

Controller rumble support

---

src/client/input/sdl.c
src/client/menu/menu.c

Since everyone is adding more stuff to the menus, I wanted to partake in it, specifically on the Game Controller / Gamepad menu.
Now the option will only appear if you have a gamepad connected, otherwise it's classic Q2 options menu:
This is how the gamepad menu looks now:
A new submenu has been added: "sticks config", which makes visible some options added in #883. The "sticks layout" spincontrol and the expo sliders have been moved here:
EDIT: unrelated text and image removed, picture updated.

More options for Gamepad menu

---

src/client/input/sdl.c

* #849 included a "#ifndef _WIN32" to fix a difference between Linux/Mac and Windows that wasn't supposed to exist. As of SDL 2.26.0, this difference has been fixed, so the "if" and the variable that it changed have been removed.
* Joysticks open with error checking, to avoid possible game crashes.
* Slight optimization for gyro aiming: some calculations only are made when needed.
* Console messages improved for game controller init: less useful text has been minimized, while more useful info is more verbose.
* Turns out, controller rumble support can be evaluated with SDL version < 2.0.18, by checking the return value of `SDL_GameControllerRumble()`: 0 rumbles, -1 doesn't.
* Speaking of `SDL_GameControllerRumble()`, now there's a check to see if it can be called, since it doesn't exist …

Game Controller code refactor

---

doc/040_cvarlist.md
src/client/header/keyboard.h
src/client/input/sdl.c
src/client/sound/header/local.h
src/client/sound/sound.c

Rumble feedback will be default.
Checked in both modes with:
* LibSDL2: 2.24.2+dfsg-1 (debian testing)
* Microntek USB Joystick (DragonRise hid-dr.ko)

Restore haptic feedback functionality.

---

CMakeLists.txt
src/common/header/common.h
src/game/savegame/savegame.c

.. which doesn't set CMAKE_GENERATOR_PLATFORM
so set YQ2ARCH in src/common/header/common.h when building with MSVC

Fix build with VisualC++'s internal CMake

---

src/client/sound/openal.c

Fix effect slot configuration #971,
Call once set reverb for change slot configuration in underwater (not for each channel)

openal: Fix reverb slot configuration

---

src/client/sound/ogg.c
src/client/sound/sound.c

Ogg file has incorrectly calculated size and samples as result calculation of volume and timings have used incorrect test samples for sterio sound.
Checked with compare ogg and wav samples from 25th Anniversary mod:
```
ffmpeg -i 25acu/sound/world/goreshit.wav 25acu/sound/world/goreshit-ogg.wav
```
Soundlist:
```
]/soundlist
(16b)  1404340(2 ch) world/goreshit.wav -11.7 dB 351.1s:15.0..0.3..1.1..2.0
(16b)  1404340(2 ch) world/goreshit-ogg.wav -11.5 dB 351.1s:15.0..18.4..1.4..2.0
```
Fixes:
* https://github.com/glhrmfrts/q25_game/issues/8
* https://github.com/yquake2/yquake2/issues/991

Fix sound characteristics calculations

---

src/client/input/sdl.c

Since @Yamagi can have "controversial features as optional features", I wanted to do this controversial PR.
https://github.com/nicman23/dkms-hid-nintendo exposes the IMU sensors of a Switch controller as a "second joystick", which makes possible to use gyro aiming on a system without having SDL 2.0.14 available (the minimum required to read controller sensors like gyro and accelerometer). This PR allows to use gyro aiming in a Raspberry Pi, or any other system with an old SDL version, by reading this "second joystick".
"Sensor reading" is still the preferred method when available, and when the time for "SDL 3 only" comes, this still makes clear which method must remain.

Gyro aiming for Switch controllers with SDL < 2.0.14

---

src/client/cl_parse.c
src/client/cl_view.c
src/client/menu/menu.c
src/client/sound/header/vorbis.h
src/client/sound/ogg.c

Playback features outlined in issue #729.
Added shuffle playback parameters to the menu:
- default - Ogg track currently active repeats. This is the quake2 default behaviour.
- play once - Ogg track currently active plays once then stops.
- sequential - Ogg tracks play in numerical order, from the currently playing track and like default, repeats.
- random - Ogg tracks play randomly, but never the same track twice.
Ogg tracks can be played from a full-screen console and tracks played will adhere to the shuffle parameter.
Loading a game map the map cd-track takes precedence as the first played track then subsequent playback of tracks will adhere to the shuffle parameter.
Any currently playing track can be overridden from the console with "`ogg play <track>`" command and subsequent playback …

Ogg Playback Features

---

src/client/sound/ogg.c
src/common/header/common.h
src/server/sv_entities.c
src/server/sv_game.c

And remove a handful of unused vars.

fix clang 16 build as C11 _NoReturn/noreturn attributes conflict.

---

src/client/cl_console.c
src/client/cl_main.c
src/client/input/sdl.c
src/client/menu/menu.c
src/client/sound/header/sound.h
src/client/sound/header/vorbis.h
src/client/sound/ogg.c
src/client/sound/sound.c

Playback features outlined in issue #715 .
Reintroduce activate\deactivate sound backend when window focus in changed. Added "windowed_pauseonfocuslost" cvar to allowing user control of pause when the window changes focus. Added "ogg_pausewithgame" cvar to allow user control of ogg playback whenever the game is paused. Introduced ogg playback command "mute" as an additional playback option for the console, command buffer and key binds.
If the window focus is changed all sound playback will stop and resume as expected. Setting "window_pauseonfocuslost" to 1 will force the game to pause when the window focus is lost, "cl_paused" is ignored in multiplayer. Setting "ogg_pausewithgame" to 1 will force ogg playback to pause whenever the game is paused. Toggling ogg mute through "ogg mute" sets …

Sound backend and ogg pause features

---

src/game/monster/parasite/parasite.c

This PR addresses issue https://github.com/yquake2/yquake2/issues/1006.
I created a new function, parasite_footstep() that checks the cvar value before playing sound_tap.
I also did these improvements:
* The parasite's walk frames did not play footsteps so I added the missing calls to parasite_footsteps
* The parasite's sight sound was getting cut off by his footsteps so I moved those to CHAN_BODY and his sight/search to CHAN_VOICE

Fixed parasites ignoring g_monsterfootsteps

---

src/game/g_combat.c
src/game/monster/boss3/boss32.c
src/game/player/hud.c
src/game/savegame/tables/gamefunc_decs.h
src/game/savegame/tables/gamefunc_list.h

This PR addresses issue https://github.com/yquake2/yquake2/issues/889.
The following changes are made:
* Removed the -999 check in Killed function to make the makron legs gibbable. Its purpose was for HUD display. Instead I added a -99 cap in the HUD code, which also fixes confusing display of negative health that is between -100 and -989, where playrs would only see the first 2 digits.
* Made the makron torso shootable and gibbable
* Makron torso is no longer spawned in a fixed location relative to the legs, now it gets traced. This prevents it from spawning inside walls.
* Makron torso is affected by gravity, so if it spawns in the air it will fall down.
* Adjusted makron legs' obscenely large hitbox to match its visual appearance better
I have tested the following scenarios:
1. Killing …

Fixed ungibbable makron parts

---

src/game/monster/boss3/boss32.c

Discovered a bug that was causing the makron torso to despawn. When the legs were gibbed, the makron entity went away, allowing a future entity like a projectile or debris, to become the new owner (same edict index as the makron was).
The fix clears the torso owner if the owner is gibbed or despawns. A more reliable fix would be to make the relationship between the legs and torso bidirectional, but this is simpler and I don't think normal gameplay can fall between the ship and the dock.
The other versions of the gibbable makron fix will have this hotfix already applied.

Fixed despawning makron torso

---

src/game/g_misc.c
src/game/monster/boss3/boss32.c

This PR addresses issue https://github.com/yquake2/yquake2/issues/1009.
Makron had no velocity applied because id's code didn't add 1 to the origin, the physics code decided the makron was touching the ground regardless of his upward velocity (might be a bug in its own right?).
The 2nd one was easily fix by copying enemy and oldenemy to the makron entity in MakronToss, and then set up the chase in MakronSpawn.
The 3rd problem was fixed by moving makron_move_sight from makron_sight to MakronSpawn. It doesn't make any sense for him to do this jump except when he's jumping out of the jorg suit.
I'm still unsure why YQ2 changed gibs to SOLID_BBOX as it causes insta-despawning gibs like with quadded RL, but it was blocking the makron's jump velocity so as a compromise fix I set gibs to …

Various fixes to makron jump sequence

---

src/client/cl_main.c

changing a bit Q_strlcpy flow as it can report wrong bytes copied if src > buffer size.

fix potential overflow on env vars settings.

---

src/game/g_combat.c
src/game/g_weapon.c

So I never liked the `VectorNormalize(dir);` call in T_Damage since the dir vector passed is often static memory like vec3_origin or entity members like the velocity vector.
So I went ahead and traced how the dir vector is used. Turns out T_damage only needs it to calculate knockback, it never leaves T_Damage's scope. So I did a rewrite and moved the knockback calculations to their own function where dir is normalized into a local variable.
I did discover one piece of code that was breaking due to this unwanted side-effect:
`VectorMA(self->s.origin, -1 * FRAMETIME, self->velocity, self->s.origin);` in bfg_touch
Due to T_Damage normalizing the BFG ball's velocity vector, this line will move the origin back 0.1 units rather than the intended 40... except when nothing is hurt by the BFG …

T_Damage no longer modifies dir parameter

---

doc/040_cvarlist.md
src/client/cl_main.c
src/game/g_main.c
src/game/header/local.h
src/game/player/weapon.c
src/game/savegame/savegame.c

I know gameplay related changes are questioned here, but I think this is a very popular issue with Quake 2, because one of the most criticized aspects of it (even among Quake series' fans) is the speed which you can change weapons. And since Quake 2 Remastered is near ([leaked by the Korean Game Rating and Administration Committee, just like with Q1 Remastered in 2021](https://www.gematsu.com/2023/06/quake-ii-remastered-rated-in-korea)), I bet that a similar option to speed up weapon switching will be included there.
Code is based on [Lithium II](https://github.com/mattayres/li2mod) and [Q2 25th Anniversary](https://github.com/glhrmfrts/q25_game). Although I say so myself, this PR has a less disruptive, better organized implementation of "fast weapon switching" than these 2 mods.

Cheat to speed up "weapon change" animations

---

src/common/shared/shared.c

Noticed that VecorNormalize2 does not output a vector if the length is 0 which is just asking for undefined behavior (my T_Damage fix made the false assumption in fact, that out would always be modified).
Its code was also redundant so I made it call the 1-arg variant to carry out the normalization.
I added these changes into the other 3 games through the T_Damage fixes.
Btw, optimization thought: Couldn't we move the sqrt call behind the length != 0 check? Would avoid sqrt for blank vectors like vec3_origin.

Fixed VectorNormalize2 not writing 0-length vectors to out

---

CMakeLists.txt

set wrongly on i386 even tough the cpu is x86`_64`.

fix cmake assumption on x86 arch.

---

src/game/player/weapon.c

https://github.com/yquake2/yquake2/pull/1049 had a definition (USHRT_MAX) included in limits.h, which has to be manually included in Linux and MacOS for it to work. The present PR fixes compilation in those platforms.
This replaces:
https://github.com/yquake2/yquake2/pull/1057
https://github.com/yquake2/yquake2/pull/1058
My apologies for the mistake.

Added missing include, fixing compilation in Linux and MacOS

---

src/client/input/sdl.c
src/client/menu/menu.c

Hopefully closes #951 , ~~alternatively you could add a third option that unpauses when the window regains focus but I decided to just make it an override for simplicity's sake.~~ Added with [cd351a0](https://github.com/yquake2/yquake2/pull/1017/commits/cd351a06023ecbbbb7e2a99d40684a65688a0a3f) 
There are three options:
Unpause on re-focus
Pause
Don't pause at all
All are available in the regular "Options" menu.
`windowed_pauseonfocuslost` is now ~~`w_pauseonfocuslost`~~ ``vid_pauseonfocuslost`` to make it easier/faster/to type by the player and more consistent with other similar options.

Pause on Minimized/Focus Lost is now in the options menu

---

src/client/curl/download.c

CL_RemoveFromQueue(qdlqueue_t *entry) free()s that entry, so the loops that call q->next after CL_RemoveFromQueue(q) are accessing free'd memory. Fix that by getting a pointer to the next entry before calling CL_RemoveFromQueue().
Also did a tiny non-functional change to CL_RemoveFromQueue() to make it easier to understand.

Fix use-after-free bugs in htttp download code

---

CHANGELOG
doc/040_cvarlist.md
src/client/refresh/gl1/gl1_main.c
src/client/refresh/gl3/gl3_sdl.c

As discussed in #1065, allowed values for this cvar are between 0 and 4, but now the game actually enforces these limits. Documentation was updated to reflect this, and the difference between `3` and `4`.
P.D.: sorry about the last commit ;)

Fixed gl1_overbrightbits limiter

---

src/backends/windows/network.c
src/client/input/sdl.c
src/client/refresh/gl1/gl1_image.c
src/client/refresh/gl3/gl3_image.c
src/client/refresh/gl3/gl3_shaders.c
src/client/refresh/soft/sw_draw.c
src/client/refresh/soft/sw_sprite.c
src/client/sound/openal.c
src/common/header/shared.h

While trying to compile the yquake2 rebased heretic2 source from @0lvin, a name conflict with min\max of different parameter counts included by a std::cpp library occurred.

Rename min\max to avoid conflict with c-plus plus

---

doc/040_cvarlist.md
src/game/g_cmds.c
src/game/g_main.c
src/game/header/local.h
src/game/savegame/savegame.c

These commands can now "count" how many times they have been called. This allows for changing to different weapons when quickly tapping their keys (or scrolling the mouse wheel), instead of going just "one down" or "one up" at a time. This is similar to how these commands operate on the recent rerelease of the game, or the old PS1 version of Q2.
The code for this is based on #865, where I did the same for `cycleweap`.
A new cvar, `g_quick_weap`, allows to enable or disable this behavior. By default, it is disabled.
This has been tested on Windows and Raspberry Pi OS.

Faster "weapprev" and "weapnext" behavior

---

src/client/cl_keyboard.c
src/client/header/keyboard.h
src/client/input/sdl.c
src/client/menu/menu.c
src/client/menu/qmenu.c

Fixes a bug where duplicate keyboard entries would occur in menu fields when using the keypad keys with num-lock on.
Menu fields now mirror behaviour of the console field.
Removed keypad left arrow case from console key ignore list.

Fix duplicate menu key keyboard entries

---

Makefile
doc/040_cvarlist.md
src/client/header/keyboard.h
src/client/input/sdl.c
src/client/menu/videomenu.c
src/client/refresh/gl1/gl1_image.c
src/client/refresh/gl1/gl1_main.c
src/client/refresh/gl1/header/local.h

Allowed values are now `0`, `1`, `2` and `4` only, since values like "3" and "0.5" generate OpenGL errors.
About the latter, these errors can finally be visible, by using the only supported method on old OpenGL: by calling `glGetError()` manually.
We do not have available something like `glDebugMessageCallbackARB` here, so by using some preprocessor magic we call `glGetError()` after every OpenGL function. Because of the ridiculous overhead this produces, this is only available when compiling with `DEBUG=1`.
At least, now there's a practical way to see if something's wrong with OpenGL 1.
This is based on the first method described here:
https://learnopengl.com/In-Practice/Debugging
You can test it by commenting the `gl1_overbrightbits` validator of the second commit, and set it to "3", …

Fixed gl1_overbrightbits limiter (for real now)

---

src/client/menu/videomenu.c
src/client/refresh/soft/sw_main.c

Add renderer specific menu options.

Texture filtering options for OpenGL and Software video modes

---

src/client/refresh/files/surf.c
src/client/refresh/gl1/gl1_light.c
src/client/refresh/gl1/header/local.h
src/client/refresh/ref_shared.h
src/client/refresh/soft/sw_light.c

Renders has global variable with the such name that used as parameters for R_MarkLights shared function.
Found by @BraXi 
Fixes:
* https://github.com/yquake2/yquake2remaster/issues/17
* https://github.com/yquake2/yquake2/issues/1093

Rename functions r_dlightframecount parameter to lightframecount

---

src/client/refresh/soft/sw_bsp.c
src/client/refresh/soft/sw_main.c
src/client/refresh/soft/sw_polyset.c

1. Fixed some instances of bmodel clipping. E.g. the cracked explodable floor in base1 because btree side detection used dist > 0 instead of dist >= 0. The infamous fan in Borehole (drawn crudely by the way and having a concave polygon) now looks ok.
2. Cleanup of alias model to scanline conversion. Basically works the same except some left-clipped triangles now have correct texture positioning (the original, duplicated code had sfrac = tfrac = 0 in one place). I wonder why no one has fixed it in so many years of better-than-320x200 displays. Also added an integer floored division routine, which is faster on x86.

Some improvements to the SW renderer

---

doc/040_cvarlist.md
src/client/refresh/gl1/gl1_image.c
src/client/refresh/gl1/gl1_lightmap.c
src/client/refresh/gl1/gl1_main.c
src/client/refresh/gl1/gl1_mesh.c
src/client/refresh/gl1/gl1_misc.c
src/client/refresh/gl1/gl1_sdl.c
src/client/refresh/gl1/gl1_surf.c
src/client/refresh/gl1/header/local.h
src/client/refresh/gl1/header/model.h
src/client/refresh/gl1/header/qgl.h
src/client/refresh/gl1/qgl.c

While it is somewhat based in the one deleted almost 8 years ago by this project, this _mtex_ implementation is a very heavy revision on it, borrowing some properties from _Knightmare's KMQuake2_ source port, like keeping all lightmaps in memory for easier manipulation.
Features:
1. It is effectively apart from the standard rendering path. One of the reasons old multitexture was so slow is that it applied lightmaps again in a second pass (`R_BlendLightmaps()` function), which is redundant, lightmaps were already bound to the second TMU in the first (supposedly only) rendering pass. That was also one of the reasons [textures appeared so bright](https://github.com/yquake2/yquake2/issues/147), and rendering was so slow. This implementation is 100% visually consistent with the "no …

GL1 multitexture

---

doc/040_cvarlist.md
src/backends/windows/system.c
src/client/refresh/gl1/gl1_image.c
src/client/refresh/gl1/gl1_lightmap.c
src/client/refresh/gl1/gl1_main.c
src/client/refresh/gl1/gl1_scrap.c
src/client/refresh/gl1/gl1_surf.c
src/client/refresh/gl1/header/local.h
src/client/refresh/gl1/header/qgl.h

Inspired by @BraXi's [idea](https://github.com/yquake2/yquake2/issues/1095), this PR allows the user to increase the lightmaps' size, having a more optimal distribution in GPU memory:
- Fewer lightmaps needed to cover the full map, which reduces the maximum number of lightmaps needed
- Less context switch change: a larger lightmap covers more surfaces, avoiding changing to a specific lightmap to start rendering.
- Fewer lightmaps mean fewer calls to `glTexSubImage2D()` when handling dynamic lights; this might be the most expensive OpenGL call the game has.
A new lightmap can reach a maximum size of 512x512, being equivalent to 16 lightmaps in the "classic" format (128x128). This, in turn, reduces the _MAX_LIGHTMAPS_ count to a minimum of 8, reducing the number of loops with some "for" …

GL1 big lightmaps and scrap

---

src/client/cl_particles.c

If CL_ClearParticles is called with zero particles, cl_particles[0-1] = -1 will have its "next" field set to NULL, potentially corrupting 4 bytes of memory at (cl_particles)-[80..76]. This may be user-manipulable but I'm not sure how bad this is in practice.

Fix potential memory corruption issue where cl_numparticles is 0 and CL_ClearParticles is called

---

doc/040_cvarlist.md
src/client/input/sdl2.c
src/client/input/sdl3.c
src/client/menu/menu.c
src/client/menu/qmenu.c
src/client/refresh/gl1/gl1_image.c
src/client/refresh/gl1/gl1_light.c
src/client/refresh/gl1/gl1_main.c
src/client/refresh/gl1/gl1_mesh.c
src/client/refresh/gl1/gl1_surf.c
src/client/refresh/gl1/header/local.h
src/client/refresh/gl1/header/qgl.h
src/client/refresh/gl3/gl3_main.c

This is a way to counter involuntary hand movements, or just a noisy signal, when using gyro aiming. Consists in a _deceleration_ applied only under a small threshold, so small rotations are dampened, being "squeezed to zero", but not completely ignored. This provides a much better feeling than a simple hard deadzone, which cuts all player rotations... including voluntary ones, losing the point of using gyro as a mouse (c'mon _Nightdive Studios_, you can do better!). Credits again to @JibbSmart for creating this ([source](http://gyrowiki.jibbsmart.com/blog:good-gyro-controls-part-1:the-gyro-is-a-mouse#toc9)).
Again, extras are included, and there are a lot for the OpenGL 1 renderer:
- _Multitexture_ bugfix: when using `hand 2` (no player weapon visible), and there were no "_alias_" models …

Gyro tightening

---

src/client/cl_download.c
src/client/sound/qal.c

also strtok_r uses its own provided buffer instead of the static one even in a somewhat monothread context, it s still better.

micro optimisations for previous security mitigations.

---

stuff/mapfixes/juggernaut/jug13.ent

This PR addresses a few map issues found as a result of bug report https://github.com/yquake2/yquake2/issues/1117
* Fixed shootable button that reveals the red key being re-shootable. Should have had a wait time of -1.
* Removed unused 4096 spawnflag from a bunch of entities.
* Fixed a broken trigger chain that intended to pull the security pass holder back into the ceiling when the key gets used to unlock the door. The trigger_key had a target of r_cl while the targetname of the trigger_relays that pull up the key holder was r_key_cl which was never targeted. The targeted name is now consistent.

Mapfix for map jug13 (The Civic Center) in Juggernaut

---

CMakeLists.txt
Makefile
doc/040_cvarlist.md
src/client/refresh/gl1/gl1_buffer.c
src/client/refresh/gl1/gl1_draw.c
src/client/refresh/gl1/gl1_image.c
src/client/refresh/gl1/gl1_light.c
src/client/refresh/gl1/gl1_main.c
src/client/refresh/gl1/gl1_mesh.c
src/client/refresh/gl1/gl1_sdl.c
src/client/refresh/gl1/gl1_surf.c
src/client/refresh/gl1/gl1_warp.c
src/client/refresh/gl1/header/local.h

_Quake III Arena_ was a revolution because of its use of "_shaders_", which doesn't refer about the "_programmable pipeline_" (the modern sense), but to the scripted features of a surface, which in backend meant the replacing of many small `glDrawArrays()` calls with a single big `glDrawElements()` call, which many OpenGL documents will agree is the preferred way to pursue an increase of performance.
The short version of the thinking behind this is: if there are a lot of `glDrawArrays()` with GL_TRIANGLE_FANs (or any other primitive) with the same texture, instead create indices that regenerate these FANs (or primitives) manually, and at the end do a `glDrawElements()` call, which use these indices to draw instead of the original vertices. May sound more expensive, but indices + vertices …

Grouped draw calls for improved performance with GL1

---

src/client/refresh/gl1/gl1_surf.c
src/client/refresh/gl1/header/model.h

First of all, my apologies for this, because I added this to the game, and it currently affects v8.40.
I thought of opening an issue for this, but since I'm responsible, I'd rather offer the solution.
As usual, for all the things I tested for PR #1124, it failed in the simplest: in `base3` map, when you reach the outdoor courtyard with the blue key door, the game hangs. The reason is the new `R_GetBrushesLighting()` function I added to the PR.
This function adds surfaces of brushes from the entity list to the lightmap chain, so the lightmap changes for brushes are done together with the world's lightmap changes, instead of doing them separately, improving the game's performance by a pretty decent margin. The problem: some of the surfaces in this list of brushes appear _more than once_, …

Infinite loop in R_GetBrushesLighting() function, hangs the game

---

src/game/g_ai.c

`Conditional jump or move depends on unitialised value(s)...HuntTarget (g_ai.c:423)...`

AI, HuntTarget fix runtime warning.

---

src/client/menu/videomenu.c

This will match the vk and gl3 menu sliders for their respective video modes.

GL4: Enable sliders for overbrights, colours and intensity

---

src/game/g_spawn.c

This PR addresses https://github.com/yquake2/yquake2/issues/1139.
This happens because `st` is reset 'before' parsing each entity in the string, so after the very last entity has been parsed, `st` won't be reset and its data remains for the rest of the level, accessible to entities spawed by for example a target_spawner, or the makron.
The fix was to simply add a `memset` after the spawn loop in `SpawnEntities`.
This issue can also apply to child entities, like for example door triggers. But those don't use any spawntemp fields as far as I know, but still worth noting for future reference.

Fixed spawntemp data leaking into mid-level spawned entities

---

src/client/sound/ogg.c

True randomness allows producing a number twice.

sound: True randomness

---

src/client/input/sdl3.c
src/client/refresh/gl1/gl1_sdl.c
src/client/refresh/gl3/gl3_sdl.c
src/client/sound/sdl.c
src/client/vid/glimp_sdl3.c

More API churn. SDL functions now return 0 for error and 1 for success, instead of -1 for error and 0 for success. Great.

Bump to SDL3 gitrev f6fc5e2

---

src/client/cl_effects.c
src/client/cl_entities.c
src/client/cl_image.c
src/client/cl_parse.c
src/client/menu/menu.c
src/client/refresh/files/pcx.c
src/client/refresh/gl1/gl1_lightmap.c
src/client/refresh/gl1/header/local.h
src/client/refresh/gl3/gl3_lightmap.c
src/client/refresh/gl3/header/local.h
src/common/filesystem.c
src/common/movemsg.c
src/server/sv_init.c

* Fix memory leak with merge skin files names in menu in #1130 
* Fix file header leak for empty file
* Small cleanup for light map format in gl* renders.
* Fix crash received message with entity id bigger than static buffer of entities.

Fix memory leaks

---

src/client/refresh/soft/sw_main.c

Regression has been  introduced in 39d2c7dbb45d53678e82baa1e727d2647d5ee755 as sdl3 has changed logic of SDL_LockTexture function call.

soft: fix texture lock

---

src/client/cl_keyboard.c
src/client/menu/header/qmenu.h
src/client/menu/menu.c
src/client/menu/qmenu.c
src/common/header/shared.h
src/common/shared/shared.c

This PR adds clipboard support and line editing extensions to menu fields (like the server address book).
CTRL actions:
* CTRL+V - Pastes clipboard into the current input field
* CTRL+C - Copies the input field content to the clipboard
* CTRL+X - Same as CTRL+C but clears the input field afterwards
* CTRL+L - Clears the current input field
Line navigation:
* Left/right arrows move the cursor left/right through the line, allowing for in-line editing
* Delete key deletes the character highlighted by the cursor
* Page End key jumps the cursor between the start and end of the current input string
And I added a new shared function, `Q_strisnum`, to test if a string is only made up of digits (for pasting input into number-only fields).
I also spotted an unsafe use of `strcpy`. When the value of …

Clipboard and in-line editing for menu input fields

---

src/client/input/sdl2.c
src/client/input/sdl3.c

Discovered that `SDL_SetClipboardText` API changed in SDL3 after the version I had been using, and it made the result of `IN_SetClipboardText` inconsistent between SDL2 and SDL3. Also added a comment to clearly define the return value of the wrapper.

Small fix for SDL3 API change for SetClipboardText

---

src/client/curl/download.c

when empty filelist downloaded from HTTP server,
CL_ParseFileList() uses unallocated buffer for strchr()
segfault happens:
0  __strchr_avx2 () at ../sysdeps/x86_64/multiarch/strchr-avx2.S:65
1  0x00007ffff743de2c in __interceptor_strchr (s=0x0, c=<optimized out>)
at ../../../../src/libsanitizer/sanitizer_common/sanitizer_common_interceptors.inc:705
2  0x000055555566d7f8 in CL_ParseFileList (dl=0x55555587a178 <cls+20984>)
at src/client/curl/download.c:484
3  0x000055555566e26c in CL_FinishHTTPDownload ()
at src/client/curl/download.c:670

fix HTTP download crash (on empty file)

---

src/client/curl/download.c

Change parameter type to match CURL lib
(prevents crash on HTTP download)
example
test server:
q2.bot.nu:27912
server config:
set sv_downloadserver "https://quake2.pages.dev/"
map DEBEQUA2
Client connects, and three files added to queue:
HTTP download: /.filelist - Queued
HTTP download: /maps/DEBEQUA2.filelist - Queued
HTTP download: maps/DEBEQUA2.bsp - Queued
from URL:
https://quake2.pages.dev/.filelist		- no file
https://quake2.pages.dev/maps/DEBEQUA2.filelist	- no file
https://quake2.pages.dev/maps/DEBEQUA2.bsp	- exists
when 404 response received for '.filelist' file,
CL_HTTP_Recv() is called and uses wrong file length in malloc()
one of tests:
==43024==ERROR: AddressSanitizer: requested allocation size 0x8000000000000000 (0x8000000000001000 after adjustments for alignment, red zones …

fix HTTP download crash (on 404)

---

Makefile
doc/030_configuration.md
doc/040_cvarlist.md
src/client/input/sdl2.c
src/client/input/sdl3.c
src/client/menu/menu.c
src/client/refresh/gl1/gl1_buffer.c
src/client/refresh/gl1/gl1_main.c
src/game/g_cmds.c

As discussed in https://github.com/yquake2/yquake2/pull/1128#issuecomment-2365045562, I took the liberty to replace the Sound Quality selector with a Sound Backend selector.
Another good reason to make this is that the current _Quality_ option... doesn't work. Try to lower the quality to _normal_, then get out of the menu, then get back to it. The reason it "gets back" to _high_ is because [the validation for quality compares s_loadas8bit](https://github.com/yquake2/yquake2/blob/master/src/client/menu/menu.c#L2257), which [never changes from 0, even if s_khz does](https://github.com/yquake2/yquake2/blob/master/src/client/menu/menu.c#L2346).
In my tests I haven't been able to break the backend. As discussed in #1135, I assume that in those systems that do, a game reboot solves it. Funnily, …

Sound backend selector + weapon preview for cycleweap

---

doc/040_cvarlist.md
src/client/cl_main.c
src/client/curl/download.c
src/client/curl/header/download.h

Disable SSL certificate check - to allow download from servers with self-signed cert, or when some certs are missing from system certificate store that CURL uses.
the assumption is: transport security is not necessary for game resources download, so Quake better be compatible with more server configurations

disable certificate validation for HTTPS

---

doc/040_cvarlist.md
src/client/cl_keyboard.c
src/client/header/client.h
src/client/header/keyboard.h
src/client/input/sdl2.c
src/client/input/sdl3.c
src/client/menu/menu.c
src/client/refresh/gl1/gl1_sdl.c

One of the "features" of old SDL2's `SDL_GameController` is that the face buttons were treated as **A/B/X/Y**, and their position didn't matter for the most part, since Nintendo gamepads exchange positions between A and B, and they also do it with X and Y.
```
(Y)              (X)
(X)   (B)        (Y)   (A)
(A)              (B)
Standard         Nintendo
```
This was kinda cool on a usability perspective, since e. g. you could always use 'A' to confirm and 'B' to cancel in menus, and you didn't have to worry about their positions. The problem: button assignments were not actually "cross-gamepad" since this inconsistency between positions will get actions really meant for the "bottom" button in the "right" button, and so on.
As many things, this didn't age well, and current SDL3's …

Consistent binding between multiple gamepad types + labels by style

---

src/game/g_func.c

This PR addresses issue reported in https://github.com/yquake2/yquake2/issues/1185.
When the button is pressed, it targets a `trigger_elevator` which works as a controller entity for `func_train` which is the elevator platform. Each button has a `pathtarget` that tells the `trigger_elevator` which `path_corner` to go to. Each `path_corner` has a pathtarget that targets the door of the respective floor. The failure here is that there is a NULL check for `activator` at the top of `door_use`. Since the elevator platform is managed by a controller entity, it has no activator set, which causes the NULL check to return early, preventing the door from opening.
This is another side-effect of all the NULL checks at the top of functions. `door_use` was needlessly checking for a NULL activator. This …

Fixed doors not being usable with NULL activator

---

src/client/input/sdl2.c
src/client/input/sdl3.c

Hi there,
I was not able to build unless adding the limits.h include. Was it missing? If there is a better solution or I did something wrong, please disregard this tiny PR.
Greetings,
MF
PS. My build config:
Build configuration
YQ2_ARCH = x86_64 COMPILER = gcc
WITH_CURL = no
WITH_OPENAL = yes
WITH_RPATH = yes
WITH_SDL3 = no
WITH_SYSTEMWIDE = no
WITH_SYSTEMDIR =

Fix missing limits header in SDL2 module

---

src/common/header/shared.h

When compiling with `CFLAGS=-std=c2x` (C23), I would run into issue:
```
src/common/shared/shared.c: In function ‘Q_stricmp’:
src/common/shared/shared.c:1019:16: error: implicit declaration of function ‘strcasecmp’; did you mean ‘Q_strcasecmp’? [-Wimplicit-function-declaration]
1019 |         return strcasecmp(s1, s2);
|                ^~~~~~~~~~
|                Q_strcasecmp
```

Add header for strcasecmp()

---

src/client/input/sdl2.c
src/client/input/sdl3.c

#1147 was made to avoid the obligatory 60Hz requirement to use Flick Stick. Unfortunately, I made a bad judgement in terms of the way the time difference calculation was made.
What was used to obtain "the current time" at execution was `cls.realtime`, which comes from `curtime` in `src/common/frame.c`, which is close but not exact enough for what is needed. This PR fixes this by using `sys_frame_time`, which is also a variation of `Sys_Milliseconds()`, but at least its calculated locally in the `sdlX.c` file, being updated more timely.
Thanks to the people at the Gyro Gaming discord for bringing this to my attention.

Small fix for Flick Stick

---

src/client/refresh/gl3/gl3_main.c

segfault on video mode changes from no fullscreen to native/fullscreen or vice-versa. memory leak on SDL init as we dlload the gl3 lib dynamically for mode changes.

gl3 issues fixes.

---

src/common/header/shared.h

C23 introduced `true` and `false` as language keywords, breaking YQ2s use of them. The first attempt to get C23 was to use the buildin `bool` type when building in C23 mode and the classic enum based `qboolean` in any other mode. This didn't take into acount, that `bool` is 1 byte long, while the enum based `qboolean` is 4 bytes long. This breaks savegames and may have impact for mods.
Fix this by always using `int` as `qboolean` and the buildin `true` and `false` types, either in their C99 or C23 variant. This way `qboolean` is always 4 bytes long and the newly introduced `true` and `false` keywords don't clash.
Suggested by @DanielGibson.
Closes #1206.

Fix C23 bool type being 1 byte long, while the enum bool is 4 bytes.

---

doc/040_cvarlist.md
src/client/cl_main.c
src/client/cl_network.c
src/client/cl_view.c
src/common/header/common.h
src/common/movemsg.c
src/server/header/server.h
src/server/sv_cmd.c
src/server/sv_game.c
src/server/sv_init.c
src/server/sv_main.c
src/server/sv_send.c
src/server/sv_user.c

This PR is my attempts to address points discussed in https://github.com/yquake2/yquake2/issues/1201 to speed up level load times, or rather, client connection times more technically speaking.
1. Model names and clients printed to console
The loops that loop through the model configstrings print out the string value to console, including empty lines that represent inline models. Each loop iteration calls `SCR_UpdateScreen` which is vey expensive.
I simply removed printing from the loops and instead just print "models" or "clients".
This change is part of the PR although @0lvin has made a commit that addresses the same issue. We can use that solution instead if preferred.
2. Message utilization
After the server receives the "new" message from a client, it will go through a process of …

Attempts to speed up level load times

---

src/game/player/client.c

I noticed the `G_Spawn` call in `SP_CreateUnnamedSpawn` was done unconditionally, so for every info_player_start in every level you load, it was spawning equally as many `noclass` entities that would never be freed.
This PR fixed that issue and I also found the code pretty copy-pasty so I wrapped it into a helper function.

Fixed SP_CreateUnnamedSpawn spawning entitiy unnecessarily

---

stuff/mapfixes/baseq2/hangar1@09a0.ent

This PR adds more mapfixes to the hangar1.ent file.
* Added missing spawnflag 1 to a few ambient `target_speaker`. These are water pumping sounds playing by the big water pipe by the water
* Fixed `trigger_push` overspeed. The default (1000) will overflow the 6-byte interger vector used by clients. 1000 * 10 * 8 = 14464 (65536 overflow bit thrown away). So I gave it a speed of 180 (14464 / 80 = 180.8), which is the actual speed it has in-game
* Added spawnflag 2048 to a bunch of non-DM entities
On a side note, I wanted to make the commander's head button permanently pressed after using the key, but there is no way to do this without code extensions as far as I know. Unless maybe using a `func_wall` to replace the button entity when using the key. I left it unchanged.

Mapfix for hangar1: Fixed target_speakers and trigger_push overspeed

---

src/game/g_ai.c
src/game/g_misc.c

This PR addresses https://github.com/yquake2/yquake2/issues/1223.
Simply setting `ideal_yaw` correctly in `FoundTarget` and `point_combat_touch` fixes the issue.

Fixed monsters acting confused while following combat points

---

.github/workflows/win32.yml
.github/workflows/win64.yml
src/client/refresh/gl1/gl1_buffer.c
src/client/refresh/gl1/gl1_image.c
src/client/refresh/gl1/gl1_lightmap.c
src/client/refresh/gl1/gl1_main.c
src/client/refresh/gl1/gl1_scrap.c
src/client/refresh/gl1/gl1_surf.c
src/client/refresh/gl1/header/local.h
src/client/refresh/gl3/gl3_main.c
src/client/refresh/gl3/gl3_mesh.c

Was mostly done in #1124, but this PR completes the cleaning job, restoring _classic Q2_ static handling of lightmaps and _scrap_ (atlas for HUD elements).
The work done by commit 4503333b should alleviate what big lightmaps used to do.
Note that the _scrap_ remains at its vanilla Q2 size (256x256), with an additional transparent border for each element inside it.
Additionally, _GL1 multitexturing_ now properly detects when a lightmap's cache reset is needed, fixes #1220 and every surface with more than 2 _static light styles_ (normal, flicker, strobe, pulse, etc.) applied to them.
Also, OpenGL's perspective projection (_frustum_) has been modified; `zNear` is down from `4` to `2` in all GL renderers, GL3 included. Fixes #1231, #1230, #1229, world hunger, and who knows what else.
It just …

Revert GL1 big lightmaps (#1108) + fixes

---

doc/040_cvarlist.md
src/client/input/sdl2.c
src/client/input/sdl3.c
src/client/menu/menu.c

This PR is a round-up of several changes for analog stick input:
- Fix invert mouse also inverting analog sticks.
- Fix non-uniform yaw/pitch scaling for analog sticks.
- Switch to commonly used FPS game conventions for representing yaw/pitch speed.
- Add a configurable outer threshold for analog sticks. Some controllers need this and it's also a prerequisite for the next item.
- Add configurable extra yaw/pitch speed at outer threshold. FPS games usually expose an option to apply additional yaw/pitch speed when the analog stick is fully tilted.
- Add a configurable ramp-up time for the above.
- Extend deadzone and snapaxis ranges (for analog sticks in poor condition).
- Add a simplified "look sensitivity" option that applies typically used yaw/pitch speed presets.
- Hide the more …

Analog stick improvements

---

doc/040_cvarlist.md
src/client/menu/videomenu.c
src/client/refresh/gl1/gl1_buffer.c
src/client/refresh/gl1/gl1_image.c
src/client/refresh/gl1/gl1_light.c
src/client/refresh/gl1/gl1_main.c
src/client/refresh/gl1/gl1_mesh.c
src/client/refresh/gl1/gl1_sdl.c
src/client/refresh/gl1/header/local.h
src/client/refresh/gl3/gl3_main.c
src/client/refresh/gl3/gl3_mesh.c

Resurrected the Vanilla Q2 gamma table. Thanks to the fact that is still applied to textures today (with `gamma value == 1.0`), getting it back was easy. The difference with the old implementation is that _alpha surfaces_ and `gl_polyblend` effects take gamma into account for their color, and most importantly, the gamma table use is no longer limited to loading textures. Now it is used for picking color intensity in lightmaps, meshes, particles, beams, and even cinematics.
It's difficult to tell apart the end result from the SDL2 gamma functions IMHO. What's noticeable is the lack of color banding at extreme values, and of course, that gamma no longer affects the whole screen, just the game window :)
The great disadvantage this has is that requires `vid_restart` to apply the new …

Gamma correction for GL1 with SDL3

---

src/client/cl_effects.c
src/client/cl_entities.c
src/client/cl_tempentities.c
src/client/header/client.h
src/client/vid/vid.c

The following was done:
* Fixes issue https://github.com/yquake2/yquake2/issues/1236.
* Temp ent static state is now cleared on renderer restarts/changes
* Added `static` to a few private functions in the temp ent code file
* Created utility functions to simply the beams/sustains code (DRY principle)
* `CL_ClearTEnt` now also `NULL`-ifies the `cl_mod_` and `cl_sfx_` static vars
* Adds a `r < 0` check for indexing `splash_color` array since `MSG_ReadByte` can return `-1`
* Temp ent global variables now `static`
* `CL_RandomFootstepSfx` and `CL_PowerScreenModel` accessor  functions, since they were needed elsewhere (exposing these variables directly is a bad idea I think)
* Renamed `playerbeam` variables and functions to the more correct `heatbeam` and cleaned up `CL_ParseHeatBeam` and …

Temp ent refactoring and temp ent model state cleared on renderer restarts

---

doc/040_cvarlist.md
src/client/input/sdl2.c
src/client/input/sdl3.c
src/client/menu/videomenu.c
src/client/refresh/gl1/gl1_image.c
src/client/refresh/gl1/gl1_light.c
src/client/refresh/gl1/gl1_main.c
src/client/refresh/gl1/gl1_mesh.c
src/client/refresh/gl1/header/local.h

Closes #953.
After having done _gamma for SDL3_, I found this issue to be very simple to solve :)
The new `gl1_minlight` cvar sets the minimum light level the rendered scene presents. Meaning, every lightmap is scaled from `0-255` to the new `threshold-255`, with the threshold being "the new 0", the new absolute minimum.
Q2, being the dark game it is, kinda loses atmosphere if you set this too high. When increased, this cvar reduces the scope of "intensities" the game is allowed to show; the higher it's set, the more it looks like `r_fullbright 1`. So, this is more useful as a visual impairment aid.
Included is a new slider in video options. As this changes presently loaded lightmaps, `vid_restart` is required.
Extra: some default values for gamepad's gyro settings have been changed.

Minimum light level for GL1

---

Makefile

When cross-compiling we'll need to use a pkgconf or pkg-config suitable for the host architecture, for example aarch64-linux-gnu-pkgconf. OS distributions typically expect to do this by setting the environment variable PKG_CONFIG, as used in Autotools.

build: Don't hard-code a specific pkg-config executable
