- src/client/cl_console.c
- src/client/cl_keyboard.c
- src/client/cl_main.c
- src/client/header/keyboard.h
I'd like some comments if you like it this way, especially now that it saves the history globally instead of per mod (if it turns out that people prefer per mod, we can just drop the last commit)
> Persistent console history

- src/client/cl_download.c
- src/client/header/client.h
- src/common/header/shared.h
- src/server/sv_save.c
without breaking savegames!
I'm so awesome.
> Set MAX_OSPATH to 4096 for !Windows + Fixes for that

- src/client/cl_screen.c
- src/client/menu/menu.c
- src/client/menu/qmenu.c
This addresses issue #87. No major refactoring with this one - just tweaks to the hard coded stuff to just get it working.
> UI scaling fixes.

- Makefile
Makefile rewrite forgot to include OpenAL folders for Darwin
> Fix broken OSX makefile

- src/client/cl_entities.c
- src/client/sound/header/sound.h
- src/client/sound/openal.c
In game noticeable when dodging blaster projectiles or missiles :)
See: https://en.wikipedia.org/wiki/Doppler_shift
> Add partial doppler shift support for 3D audio sources.

- src/backends/sdl/input.c
- src/client/cl_cin.c
- src/client/cl_keyboard.c
- src/client/header/keyboard.h
- src/client/menu/menu.c
- src/client/refresh/files/pcx.c
As example first button(...,back:b1,...) in SDL_GAMECONTROLLERCONFIG
Quit from game by press any button on joystick in "quit dialog".
> Add support for use controller back button as ESC

- src/common/cvar.c
working ok on Linux and others.
> bus error fix when quitting. spotted on openbsd while

- src/client/cl_screen.c
- src/client/refresh/gl1/gl1_light.c
- src/client/refresh/gl1/gl1_model.c
- src/client/refresh/soft/header/local.h
- src/client/refresh/soft/header/model.h
- src/client/refresh/soft/sw_aclip.c
- src/client/refresh/soft/sw_alias.c
- src/client/refresh/soft/sw_bsp.c
- src/client/refresh/soft/sw_draw.c
- src/client/refresh/soft/sw_edge.c
- src/client/refresh/soft/sw_image.c
- src/client/refresh/soft/sw_light.c
- src/client/refresh/soft/sw_main.c
- src/client/refresh/soft/sw_misc.c
- src/client/refresh/soft/sw_model.c
- src/client/refresh/soft/sw_part.c
- src/client/refresh/soft/sw_poly.c
- src/client/refresh/soft/sw_polyse.c
- src/client/refresh/soft/sw_rast.c
- src/client/refresh/soft/sw_scan.c
- src/client/refresh/soft/sw_sprite.c
- src/client/refresh/soft/sw_surf.c
Removed unused function and variables and added 'static' to local variables and functions.
> Soft render clean up.

- src/backends/unix/network.c
- src/backends/windows/network.c
- src/client/cl_network.c
- src/client/menu/menu.c
- src/common/header/common.h
By making sure the corresponding cvars ("adr0", "adr1", ..., "adr8") are always initialized.
> Don't forget entries of Multiplayer "Address Book"

- src/backends/unix/system.c
based on https://github.com/voidlinux/void-packages/pull/13012/files
> fix compilation on musl libc.

- src/client/refresh/files/wal.c
- src/client/refresh/gl1/gl1_image.c
- src/client/refresh/gl3/gl3_image.c
- src/client/refresh/soft/header/local.h
- src/client/refresh/soft/sw_image.c
- src/client/refresh/soft/sw_main.c
- src/client/refresh/soft/sw_misc.c
- src/client/refresh/soft/sw_part.c
- src/client/refresh/soft/sw_surf.c
- src/common/clientserver.c
- src/common/header/common.h
* window height as multiple for particles size.
*  Add custom particle shape by sw_custom_particles.
0 - use rectangle (default shape)
1 - use hexagon
> Fixes scale particles in soft render

- src/backends/unix/network.c
> - Fix addrinfo leaks.

- src/client/sound/ogg.c
> Fix segfault in OGG_PlayTrack when ogg_enable is set to zero

- src/client/menu/menu.c
Allow numeric input of "capturelimit" cvar and toggling of CTF dmflags via menu system as follows:
1. "start network server" menu
- Remove "rules" selection from "start network server" menu.  (No coop support in CTF; defaults to deathmatch.)
- Add input box for "capturelimit."
2. "deathmatch flags" menu
- Remove flags ignored in CTF: "teamplay" & "friendly fire."
- Add toggling of "force join," "armor protect," and "no techs" dmflags.
Existing var names & dmflag definitions for Rogue support were re-used since they're otherwise idle in CTF.
> Add support for CTF options to "start network server" menu.

- src/backends/unix/network.c
- src/backends/windows/network.c
- src/client/menu/menu.c
- src/client/refresh/soft/sw_image.c
- src/client/refresh/soft/sw_main.c
- src/game/g_items.c
- src/game/player/hud.c
* Add support retexturing for software render(disabled by default)
* code clean up by cppcheck validation
* remove `sw_maxedges`, `sw_maxsurfs` as we always reallocate buffers if see size problems.
> Cppcheck fixes

- src/client/menu/menu.c
> Use separator instead action in delete menu header

- src/win-wrapper/wrapper.c
because it sucks when you start quake2.exe and the game starts in the background
> quake2.exe wrapper puts Q2 window in foreground

- src/client/refresh/soft/header/local.h
- src/client/refresh/soft/header/model.h
- src/client/refresh/soft/sw_bsp.c
- src/client/refresh/soft/sw_draw.c
- src/client/refresh/soft/sw_edge.c
- src/client/refresh/soft/sw_light.c
- src/client/refresh/soft/sw_main.c
- src/client/refresh/soft/sw_misc.c
- src/client/refresh/soft/sw_model.c
- src/client/refresh/soft/sw_part.c
- src/client/refresh/soft/sw_poly.c
- src/client/refresh/soft/sw_rast.c
- src/client/refresh/soft/sw_scan.c
- src/client/refresh/soft/sw_surf.c
* fix mips select in Sonic Mayhem
* provide copy rectangle in SDL_RenderCopy
* skip frames without changes
* clean up sw_bsp.c
> Soft render speed up

- src/client/refresh/soft/header/local.h
- src/client/refresh/soft/sw_aclip.c
- src/client/refresh/soft/sw_alias.c
- src/client/refresh/soft/sw_draw.c
- src/client/refresh/soft/sw_image.c
- src/client/refresh/soft/sw_main.c
- src/client/refresh/soft/sw_model.c
- src/client/refresh/soft/sw_surf.c
Fix warnings generated by PVS studio and cppcheck.
> Make static C code analysis tool little more happy(#426)

- src/game/g_ai.c
This pull request fixes bug https://github.com/yquake2/yquake2/issues/460. I will provide ones for xatrix and rogue as well.
> Fix monsters not changing state after enemy goes away

- src/game/g_spawn.c
- src/game/monster/boss3/boss32.c
This pull request fixes bug https://github.com/yquake2/yquake2/issues/466.
> Fixed medics unable to heal makrons

- src/game/monster/float/float.c
Noticed this subtle error in the floater zap damage fix.
> Added missing '== RANGE_MELEE'

- src/game/g_cmds.c
This pull request adds the command cycleweap, suggested in https://github.com/yquake2/yquake2/issues/471.
Example use: bind 2 cycleweap weapon_shotgun weapon_supershotgun
> Added cycleweap command for generalized xatrix-like weapon switching

- src/game/player/weapon.c
This pull request addresses the inconsistency reported in https://github.com/yquake2/yquake2/issues/470.
> Quad sound for quadded hand grenades

- doc/050_commands.md
- src/client/menu/menu.c
I was only going to add my name to the credits for this PR but I saw some important information missing from the documentation for my cycleweap command so I provided some extra text there as well.
> Added some text to cycleweap doc and added name to credits

- src/client/refresh/soft/sw_main.c
Fixes bug with update only horizontal line with brightness slider in menu.
> Add force redraw on change gamma

- src/game/g_monster.c
Baseq2 version of the improvements listed in PR https://github.com/yquake2/rogue/pull/61.
> Monster frame handling improvements

- src/backends/unix/system.c
- src/backends/windows/system.c
- src/client/refresh/files/stb_image.h
- src/client/refresh/files/stb_image_resize.h
- src/client/refresh/gl1/gl1_main.c
- src/client/refresh/gl3/gl3_main.c
- src/client/refresh/soft/sw_main.c
- src/client/sound/header/stb_vorbis.h
- src/client/sound/ogg.c
- src/client/vid/header/stb_image_write.h
- src/game/g_main.c
- src/server/sv_game.c
- src/server/sv_send.c
* port not specific to Vulkan changes from ref_vk branch
* fix segmentation fault on device without sound card, ogg_shuffle is not initialized.
* update stb_* codes
* use snprintf with buffers
> Small fixes

- src/client/cl_screen.c
- src/client/cl_view.c
- src/client/refresh/gl1/gl1_main.c
- src/client/refresh/gl3/gl3_main.c
- src/client/refresh/soft/header/local.h
- src/client/refresh/soft/sw_main.c
- src/client/refresh/vk/header/vk_local.h
- src/client/refresh/vk/header/vk_model.h
- src/client/refresh/vk/vk_common.c
- src/client/refresh/vk/vk_draw.c
- src/client/refresh/vk/vk_image.c
- src/client/refresh/vk/vk_light.c
- src/client/refresh/vk/vk_mesh.c
- src/client/refresh/vk/vk_model.c
- src/client/refresh/vk/vk_rmain.c
- src/client/refresh/vk/vk_rmisc.c
- src/client/refresh/vk/vk_rsurf.c
- src/client/vid/header/ref.h
- src/client/vid/vid.c
* gamma of 3d surfaces changed without restart render #505
* make more functions static
* fix popup menu
> Fix open multiplayer

- src/client/refresh/gl1/gl1_image.c
- src/client/refresh/gl1/header/local.h
- src/client/refresh/soft/header/local.h
- src/client/refresh/soft/sw_main.c
- src/client/refresh/soft/sw_model.c
* small cleanup in soft render for make cppcheck happy
* reuse resize code in gl1 render
> Small cleanup

- src/client/refresh/soft/sw_main.c
On MacOS texture is cleaned up after render and code have to copy a whole
screen to the texture, other platforms save previous texture content and can
be copied only changed parts.
> MacOS softrender fixes #541.

- src/client/vid/glimp_sdl.c
- src/common/filesystem.c
* Fix for #546
* Dynamically allocate memory on PAK directory read 
* Make MAX_FILES_IN_PACK soft limit for archives.
> Dynamically allocate memory on PAK directory read 

- doc/050_commands.md
- src/server/sv_cmd.c
Added command 'listmaps' to list available maps to load through the console. It will list maps in pak files first followed by maps in the 'maps/' folder from baseq2 or mod or expansion being played.
> added listmaps command

- src/backends/generic/misc.c
using more straightforward approach to get the current binary path.
Actual approach more fit to get other infos (e.g. address mappings and so on).
> Haiku support, code simplification.

- src/client/refresh/vk/header/local.h
- src/client/refresh/vk/header/util.h
- src/client/refresh/vk/vk_common.c
- src/client/refresh/vk/vk_device.c
- src/client/refresh/vk/vk_image.c
- src/client/refresh/vk/vk_mesh.c
- src/client/refresh/vk/vk_rmain.c
- src/client/refresh/vk/vk_util.c
- src/client/refresh/vk/vk_warp.c
* Add support for `gunfov` and `farsee`
* Support suballocate image in memory block.
> Rework memory allocation

- src/client/refresh/files/stb.c
- src/client/refresh/ref_shared.h
- src/client/refresh/vk/header/util.h
- src/client/refresh/vk/vk_common.c
- src/client/refresh/vk/vk_draw.c
- src/client/refresh/vk/vk_rmain.c
- src/client/refresh/vk/vk_util.c
* Fix multiplayer -> player setup menu rendering
* Cinema scaling with near color filtering
>  Vulkan improvements

- src/client/refresh/files/wal.c
- src/client/refresh/gl1/gl1_image.c
- src/client/refresh/gl1/gl1_misc.c
- src/client/refresh/gl1/gl1_model.c
- src/client/refresh/gl1/gl1_sp2.c
- src/client/refresh/gl1/gl1_warp.c
- src/client/refresh/gl3/gl3_image.c
- src/client/refresh/gl3/gl3_model.c
- src/client/refresh/gl3/gl3_warp.c
- src/client/refresh/gl3/header/local.h
- src/client/refresh/ref_shared.h
- src/client/refresh/soft/header/local.h
- src/client/refresh/soft/sw_draw.c
- src/client/refresh/soft/sw_image.c
- src/client/refresh/soft/sw_main.c
- src/client/refresh/soft/sw_model.c
- src/client/refresh/soft/sw_scan.c
- src/client/refresh/soft/sw_surf.c
- src/client/refresh/vk/header/local.h
- src/client/refresh/vk/header/model.h
- src/client/refresh/vk/vk_image.c
- src/client/refresh/vk/vk_model.c
- src/client/refresh/vk/vk_warp.c
- src/common/cvar.c
- src/common/header/files.h
- src/common/shared/shared.c
- src/game/g_turret.c
- src/game/player/client.c
- src/game/savegame/tables/gamefunc_decs.h
* scale intro in software render
* use smooth filtering for final image in software render
* general fixes based on cppcheck and -flto warnings
* add m8 textures support for heretic based modes
* improve models load
* rework map load and models caching in ref_vk
> Port improvements to soft and vulkan

- src/client/refresh/soft/sw_main.c
- src/client/refresh/vk/vk_rmain.c
- src/client/sound/header/sound.h
- src/client/sound/header/vorbis.h
- src/client/sound/ogg.c
- src/client/sound/openal.c
- src/client/sound/qal.c
- src/client/sound/sdl.c
- src/client/sound/sound.c
- src/client/sound/wave.c
* validate count of audio channels (only mono/stereo audio are supported)
* make internal functions static.
> Support of wav stereo sound

- src/client/refresh/soft/header/local.h
- src/client/refresh/soft/sw_draw.c
- src/client/refresh/soft/sw_edge.c
- src/client/refresh/soft/sw_main.c
- src/client/refresh/soft/sw_misc.c
- src/client/refresh/soft/sw_part.c
- src/client/refresh/soft/sw_poly.c
- src/client/refresh/soft/sw_polyset.c
- src/client/refresh/soft/sw_scan.c
- src/client/refresh/soft/sw_surf.c
- src/client/refresh/vk/vk_rmain.c
#661 - save buffer size and scale selected resolution to desktop aspect ratio.
> Soft render updates

- src/backends/generic/misc.c
enabling "RunFast" mode ; benefits might depend on the board
at hand.
> Little optimisation attempt targeted only for ARM 32 bits,

- src/client/cl_keyboard.c
- src/client/header/keyboard.h
- src/client/input/sdl.c
- src/client/vid/glimp_sdl.c
- src/common/cmdparser.c
- src/common/cvar.c
- src/common/filesystem.c
- src/common/frame.c
- src/common/header/common.h
Most of these are probably "harmless", but I could definitely see the missing/improper SDL_Quit/SDL_QuitSubsystem causing headaches later.
EDIT: I thought this was pretty small, but I could break down each leak fix into individual commits if that's preferable and redo the pull request.
EDIT 2: I also do hope this doesn't fall into the category of "unnecessary cleanups" per contributing guidelines. This isn't really a refactor which is what I think that's referring to. But if that's not the case, I'm sorry I could just fix the ones introduced specifically by yquake2.
> Fix some leaks

- src/client/header/keyboard.h
- src/client/input/sdl.c
- src/client/sound/header/local.h
- src/client/sound/openal.c
- src/client/sound/sdl.c
- src/client/sound/sound.c
Sync haptic feedback with original delay/attack/fade/volume/length of sound and remove effect hard coded haptic effects.
> Sync haptic feedback with sound track

- src/client/refresh/soft/header/local.h
- src/client/refresh/soft/header/model.h
- src/client/refresh/soft/sw_image.c
- src/client/refresh/soft/sw_main.c
- src/client/refresh/soft/sw_model.c
- src/client/refresh/soft/sw_rast.c
- src/client/refresh/soft/sw_scan.c
- src/client/sound/sound.c
* use SmoothColorImage as sw_anisotropic filtering replacement
* port preserve image/model code from vulkan render.
> Preserve sounds/maps and images on map change

- doc/020_installation.md
> installatio doc update proposal, regarding BSD and Solaris

- src/game/player/weapon.c
This PR addresses issue https://github.com/yquake2/yquake2/issues/763 and also improves code stability.
* Added a safety check to make sure the entity making the noise is actually a player
* Made spawning of player_noise entities optional. If they fail to spawn, PlayerNoise() will not cause any sound event
* Each time PlayerNoise() is called it will verify the mynoise variables of the player, and make an effort to repair them if needed
* mynoise and mynoise2 can now be differentiated by spawnflags. self/weapon noises have none, while impact noises have spawnflag 1 set. This will help verification to re-link the noises correctly to the player in cases where impact noise appears first in the entity list. This is not crucial however, if the linking is incorrect it will correct itself quickly …
> Fixed player_noise entity leak and improved stability surrounding player noises

- src/client/cl_main.c
- src/client/curl/download.c
- src/client/curl/header/download.h
displaying download progress based on a new cvar, 0 by default.
> client curl update proposal.

- src/client/cl_main.c
- src/client/refresh/gl1/gl1_light.c
- src/client/refresh/gl1/gl1_main.c
- src/client/refresh/gl3/gl3_light.c
- src/client/refresh/gl3/gl3_main.c
- src/client/refresh/soft/header/local.h
- src/client/refresh/soft/sw_alias.c
- src/client/refresh/soft/sw_image.c
- src/client/refresh/soft/sw_main.c
- src/client/refresh/soft/sw_model.c
- src/client/refresh/soft/sw_polyset.c
- src/common/cvar.c
Replace wall textures to white texture to implement gl_lightmap from gl1 render.
Skin textures are left without changes.
> soft: add r_lightmap implementation

- CMakeLists.txt
the compiler from to one particular frontend since it can
happen to have differents for C and C++.
> cmake limiting the scope of concern to C only and detecting

- CMakeLists.txt
- src/backends/windows/system.c
- src/client/refresh/gl1/gl1_main.c
- src/client/refresh/gl1/gl1_mesh.c
- src/client/refresh/gl1/gl1_misc.c
- src/client/refresh/gl1/gl1_surf.c
- src/client/refresh/gl1/gl1_warp.c
- src/client/refresh/gl3/gl3_main.c
- src/client/refresh/gl3/gl3_misc.c
- src/client/refresh/ref_shared.h
- src/client/sound/sound.c
- src/client/vid/glimp_sdl.c
- src/client/vid/header/ref.h
- src/common/filesystem.c
- src/common/header/common.h
- src/common/header/shared.h
- src/common/shared/shared.c
No idea if we want this, and I haven't tested it *that* much (but a bit at least), but it should generally be in an ok-ish shape now (no more `alloca()` in loops and such).
Also fixed some general issues in the CMakeLists.txt, like properly detecting the target CPU
~~Unfortunately, it currently requires VS2019 16.8 or newer; maybe this could be reduced to VS2015, if we can find a working alternative for `_Alignas(TYPE)` that doesn't require C11..~~
(`#define YQ2_ALIGNAS_TYPE( TYPE )  __declspec(align(__alignof(TYPE)))` looks like it should work, but doesn't, some compiler error about __builtin_alignof or sth like that)
**UPDATE:** Pushed a hack that should make it work with VS2015 and newer
Thanks to @bartekordek in #791 for inspiring me to dust up my [old hacky msvc …
> Support building with Visual Studio (via CMake)

- src/common/frame.c
expanding to powerpc archs also for visual studio/MSVC while
keeping clang support for windows.
> frame cpu pause refactoring.

- src/common/frame.c
Updates for #742 with hardcoded maxfps in benchmark mode
> Remove framelimits for timedemo

- src/client/menu/header/qmenu.h
- src/client/menu/menu.c
- src/client/menu/qmenu.c
Quality of life improvement, this makes the code easier to read, and see how the retained mode menu functions.
> Add menu bitmap support

- src/client/menu/qmenu.c
> Iterate once through menu item list

- src/client/menu/header/qmenu.h
- src/client/menu/qmenu.c
Makes code more readable and removes some unused stuff.
> UI code maintenance

- doc/040_cvarlist.md
- doc/050_commands.md
- src/client/cl_main.c
- src/client/menu/menu.c
- src/game/g_cmds.c
* Spawn entity by coordinates: `spawnentity`
* Spawn entity to start point: `spawnonstart`
* Add optional animation for player model preview.
> Add new cheats spawn commands

- src/client/menu/menu.c
Closes #892 
Also, avoids asking for deletion in "\<empty\>" savegames.
> Quicksaves can be deleted from menu

- src/game/g_cmds.c
The flood_msgs cvar's value was being used unguarded, so if it was set to something outside the range [0, 10] undefined hehavior will happen next time a player talks, either a crash or a memory corruption that leads to weird stuff/crash.
This PR addresses the issue, and I also made players in single-player able to talk to themselves as much as they like.
> Prevent crash or memory corruption when flood_msgs is too high or too low

- src/game/g_phys.c
This PR addresses the issue where entities can phase through solid geometry. Players mostly experience this as dead bodies stopping elevators and falling through them. There was a previous attempt to fix this in the code but it didn't work in practice.
The general problem is that startsolid traces treat different obstructing volumes as continuous solidity, even if the volumes have different content types. So for example when the player steps on a dead body in an elevator, now the player bbox and the elevator are treated as a continuous volume that startsolid tries to trace through looking for non-solid space.
A good solution is not possible without game API changes, but a simple work-around is to make a 2nd trace attempt if the trace is startsolid. This 2nd attempt will only collide with …
> Prevent dead bodies from obstructing elevators

- src/client/input/sdl.c
> pause the game when window is minimized.

- src/backends/unix/system.c
- src/backends/windows/system.c
- src/common/clientserver.c
- src/common/frame.c
Usecase: show map name on level load
> Unix: Add color output for console

- doc/040_cvarlist.md
- src/client/cl_main.c
- src/client/header/client.h
- src/client/sound/openal.c
- src/client/sound/sdl.c
ought to go on or not when the game pauses.
> Introduces new cvar cl_audiopaused to control if the audio loop

- doc/020_installation.md
> Seperated mapfixes text from monster footstep text

- Makefile
- src/client/refresh/files/models.c
- src/client/refresh/files/surf.c
- src/client/refresh/files/wal.c
- src/client/refresh/gl1/gl1_light.c
- src/client/refresh/gl1/gl1_main.c
- src/client/refresh/gl1/gl1_model.c
- src/client/refresh/gl1/gl1_surf.c
- src/client/refresh/gl1/header/local.h
- src/client/refresh/gl1/header/model.h
- src/client/refresh/gl3/gl3_light.c
- src/client/refresh/gl3/gl3_main.c
- src/client/refresh/gl3/gl3_model.c
- src/client/refresh/gl3/gl3_surf.c
- src/client/refresh/gl3/header/local.h
- src/client/refresh/gl3/header/model.h
- src/client/refresh/ref_shared.h
- src/client/refresh/soft/header/local.h
- src/client/refresh/soft/header/model.h
- src/client/refresh/soft/sw_bsp.c
- src/client/refresh/soft/sw_image.c
- src/client/refresh/soft/sw_light.c
- src/client/refresh/soft/sw_main.c
- src/client/refresh/soft/sw_misc.c
- src/client/refresh/soft/sw_model.c
- src/client/refresh/soft/sw_surf.c
- src/common/cvar.c
Additional code sharing between renders.
> Shared models logic

- src/game/monster/gladiator/gladiator.c
Fixes issue https://github.com/yquake2/yquake2/issues/995.
> Fixed stand-ground gladiators not attacking within a certain range

- src/game/g_ai.c
Fixes issue https://github.com/yquake2/yquake2/issues/1000.
* Monsters lose interest in their player enemy when players enter intermission
* FindTarget ignores player candidates during intermission
I also moved the !client check in FindTarget down to where the !client->inuse check is, reducing risk of crashes.
> Fixed monsters seeing players during intermissions

- src/game/monster/boss3/boss32.c
Introduced in PR https://github.com/yquake2/yquake2/pull/1010.
FoundTarget was not being called if makron's enemy was out of sight at the time of spawn, causing glitchy AI. Was a simple logic error on my part - was putting the FoundTarget stuff behind the visible() condition.
In addition to fixing that, I improved the enemy transfer code and made the makron remember where he last saw his enemy before the jorg suit was destroyed.
Tested in-game and his AI behaves correctly, both if you are in sight or hiding. When hiding he'll go for the last sighting spot and then the player trail as expected.
This will already be in the PRs for the other games.
> Fix for AI bug introduced by new makron jump code

- src/client/refresh/gl3/gl3_main.c
- src/client/refresh/gl3/gl3_mesh.c
- src/common/header/shared.h
- src/common/shared/shared.c
and convert some runtime which deserve to be evaluated earlier.
> adding compile time assertion support whenever possible

- src/client/cl_cin.c
- src/client/refresh/files/models.c
- src/client/refresh/gl1/gl1_draw.c
- src/client/refresh/gl1/header/local.h
- src/client/refresh/gl3/gl3_draw.c
- src/client/refresh/gl3/header/local.h
- src/client/refresh/soft/header/local.h
- src/client/refresh/soft/sw_draw.c
- src/client/refresh/soft/sw_image.c
- src/client/refresh/soft/sw_main.c
- src/client/vid/header/ref.h
- src/client/vid/vid.c
Add support of JPG/PNG format and small cleanup in soft render.
> Cinematic JPG/PNG image support

- src/client/menu/menu.c
- src/common/header/shared.h
- src/common/shared/shared.c
Case insensitive compare in quicksort compare function for player names.
Closes #1082
> Case insensitive sort for player skins

- src/client/menu/videomenu.c
Adds texture filtering option to the video menu.
Closes #753
> Texture filtering option

- doc/040_cvarlist.md
- src/client/cl_entities.c
- src/client/cl_main.c
- src/client/cl_tempentities.c
- src/client/header/client.h
Adds the cvar suggested in https://github.com/yquake2/yquake2/issues/1098.
> Added cvar cl_laseralpha and documentation in cvarlist

- src/client/vid/vid.c
Fix regression introduced in e61d9444c
https://github.com/yquake2/yquake2/issues/1097
> client: fix gles3 name

- src/client/menu/menu.c
- src/common/cmdparser.c
- src/server/sv_cmd.c
Additionally add long (QPATH) skin preview.
If some of multiplayer map is already loaded, weapon is changed each 9 seconds. In other case weapon.md2 is showed.
> Show weapon in player model preview

- Makefile
- stuff/cmake/modules/FindSDL2.cmake
This will fix issue #867.
Should work on both macOS / Darwin with Intel CPUs and on Apple Silicon (tested).
> Update Makefile to build on Apple Silicon

- src/client/cl_cin.c
- src/client/refresh/files/pcx.c
- src/client/refresh/soft/header/local.h
- src/client/refresh/soft/sw_alias.c
- src/client/refresh/soft/sw_polyset.c
Add use byte per line in pcx loader #1119
Fix apply skin with incorrect ratio to model in soft skin
> Improve pcx support and cleanup soft render

- src/client/cl_console.c
> console: Fix cursor timestep

- .gitignore
- src/client/input/sdl2.c
- src/client/input/sdl3.c
Just like it was done in ioquake/ioq3@9fbbf42.
> Fix Windows key bind name on non-Mac

- src/client/input/sdl3.c
- src/client/refresh/gl1/gl1_sdl.c
- src/client/refresh/gl3/gl3_sdl.c
- src/client/refresh/soft/sw_main.c
- src/client/vid/glimp_sdl3.c
According to [this](https://github.com/libsdl-org/SDL/releases/tag/preview-3.1.3), SDL3's ABI will become stable soon. So I've bumped the support for yquake2.
> Bump to SDL3 gitrev 8db3b47

- CMakeLists.txt
- src/backends/generic/misc.c
- src/client/refresh/soft/sw_main.c
- src/client/vid/glimp_sdl2.c
I also improved the logging of a couple of uncommon errors and warnings
> Simplify compiling for targets that lack GL drivers

- .github/workflows/win32.yml
- .github/workflows/win64.yml
- src/client/input/sdl3.c
Detected by ASAN=1
Build Win64-SDL3 as part of github actions
> sdl3: Fix memory leak in IN_Controller_Init

- .github/workflows/win_msvc.yml
> Github workflow for Visual Studio build

- src/client/cl_console.c
- src/client/cl_download.c
- src/client/header/client.h
- src/client/refresh/gl1/gl1_image.c
- src/client/refresh/gl1/header/local.h
- src/client/refresh/gl3/gl3_image.c
- src/client/refresh/soft/sw_image.c
- src/client/sound/header/local.h
- src/client/sound/header/sound.h
- src/client/sound/ogg.c
- src/client/sound/openal.c
- src/client/sound/sdl.c
- src/client/sound/sound.c
- src/common/cvar.c
- src/common/header/shared.h
- src/common/pmove.c
Add const and static where possible
> Backport changes from yquake2remaster

- src/client/cl_main.c
- src/client/cl_view.c
- src/client/header/client.h
- src/common/header/common.h
- src/common/movemsg.c
- src/common/szone.c
- src/server/header/server.h
- src/server/sv_cmd.c
- src/server/sv_conless.c
- src/server/sv_entities.c
- src/server/sv_game.c
- src/server/sv_init.c
- src/server/sv_main.c
- src/server/sv_save.c
- src/server/sv_send.c
- src/server/sv_user.c
- src/server/sv_world.c
Make more server and client local functions static
> fix discard const warning in MSG_WriteString

- src/client/cl_effects.c
- src/client/cl_parse.c
- src/client/cl_view.c
- src/client/menu/menu.c
- src/client/menu/qmenu.c
- src/client/menu/videomenu.c
- src/client/refresh/soft/sw_alias.c
- src/client/refresh/soft/sw_draw.c
- src/client/refresh/soft/sw_poly.c
- src/client/sound/sound.c
- src/common/movemsg.c
> fix of coverity detected issues

- .github/workflows/codeql.yml
- .github/workflows/linux_aarch64.yml
- .github/workflows/linux_x86_64.yml
- .github/workflows/macos.yml
- .github/workflows/win32.yml
- .github/workflows/win64.yml
- .github/workflows/win_msvc.yml
- CMakeLists.txt
* Fix curl 32 bit download,
* Fix workflow run for forks with custom name
* Enable CodeQL and PREfast validation
* Use github-cli instead wget
> workflows: update workflows
